"""
Boldpiq check knowledge base.

Every check the scanner can return, explained in plain English for a business
owner: what it is, why it costs or makes money, and what the fix involves.

Format:  id: (Title, priority, effort, why_it_matters, how_to_fix)
    priority: critical | high | medium | low
    effort:   low | medium | high   (how much work the fix is)

This text is Boldpiq's own. Anything not listed here falls back to the
scanner's raw finding line, so the report never has a blank spot.
"""

CRITICAL, HIGH, MEDIUM, LOW = "critical", "high", "medium", "low"
LO, ME, HI = "low", "medium", "high"

CHECKS = {

# ── SEO :: meta ──────────────────────────────────────────────────────────────
"title_exists": ("Page title tag", CRITICAL, LO,
    "The title is the blue clickable headline in Google results and the text on the browser tab. It is the single strongest on-page ranking signal, and with no title Google invents one from your page content — usually badly.",
    "Add a <title> inside <head> with the main service and location, 50-60 characters."),
"title_length": ("Title length", HIGH, LO,
    "Titles over roughly 60 characters get cut off mid-sentence in results, and very short ones waste prime advertising space. Length directly moves click-through rate.",
    "Rewrite to 30-60 characters, most important words first so nothing valuable is lost to truncation."),
"desc_exists": ("Meta description", HIGH, LO,
    "This is the two-line sales pitch under your Google listing. It is not a ranking factor, but it decides whether the searcher clicks you or the competitor below you.",
    'Add <meta name="description" content="..."> with a benefit and a reason to click, 120-160 characters.'),
"desc_length": ("Meta description length", MEDIUM, LO,
    "Under 120 characters leaves free advertising space unused; over 160 gets truncated so your call to action never gets read.",
    "Rewrite to 120-160 characters, front-loading the offer."),
"viewport": ("Mobile viewport tag", CRITICAL, LO,
    "Without this tag phones render the page at desktop width and shrink it, so text is unreadable and buttons unusable. Most local search traffic is mobile, and Google indexes the mobile version first.",
    'Add <meta name="viewport" content="width=device-width, initial-scale=1"> to <head>.'),
"charset": ("Character encoding", MEDIUM, LO,
    "Without a declared charset, accented characters and currency symbols can render as garbled boxes, which looks broken and unprofessional.",
    'Add <meta charset="utf-8"> as the first tag in <head>.'),
"lang_attr": ("Page language attribute", MEDIUM, LO,
    "Tells search engines and screen readers which language the page is in, which affects which country's results you appear in and how AI assistants handle your content.",
    'Set <html lang="en-ZA"> (or the correct locale) on the html tag.'),
"theme_color": ("Browser theme colour", LOW, LO,
    "Colours the browser chrome on mobile to match your brand. Small polish signal, no ranking effect.",
    'Add <meta name="theme-color" content="#yourbrandhex">.'),
"meta_refresh": ("Meta refresh redirect", HIGH, LO,
    "Meta refresh redirects are treated as a spam signal and pass little or no ranking value from the old URL.",
    "Replace with a proper server-side 301 redirect."),
"robots_meta": ("Robots meta directive", CRITICAL, LO,
    "This tag can silently tell Google not to index the page at all. A stray noindex left over from a staging site is one of the most common causes of a site vanishing from search.",
    'Ensure the page uses "index, follow" unless it genuinely should be hidden.'),
"meta_keywords": ("Meta keywords tag", LOW, LO,
    "Google has ignored this tag since 2009, and it publicly advertises your target keywords to competitors.",
    "Delete the meta keywords tag."),
"meta_viewport_content": ("Responsive viewport value", HIGH, LO,
    "The viewport tag only works properly when it includes width=device-width. Without it, the mobile layout can still break.",
    "Include width=device-width, initial-scale=1 in the viewport content."),
"max_image_preview": ("Large image previews", LOW, LO,
    "Allows Google to show a large image thumbnail beside your listing and in Discover, which measurably lifts clicks on visual businesses.",
    'Add max-image-preview:large to the robots meta tag.'),
"title_desc_duplicate": ("Title vs description overlap", MEDIUM, LO,
    "When the description repeats the title word for word you waste the second line of your listing instead of adding a new reason to click.",
    "Rewrite the description to add information the title does not already give."),

# ── SEO :: content ───────────────────────────────────────────────────────────
"h1_exists": ("Main H1 heading", CRITICAL, LO,
    "The H1 is the on-page headline that tells both visitors and search engines what this page is about. Missing it, or having several competing H1s, muddies the page's topic.",
    "Use exactly one H1 per page containing the primary service or offer."),
"title_h1_alignment": ("Title and H1 alignment", HIGH, LO,
    "When the browser title and the on-page headline share no words, search engines get two different answers to 'what is this page about' and rank the page for neither confidently. It also creates a jarring mismatch for the visitor who clicked.",
    "Rewrite so the title and H1 share the same two or three key terms."),
"h2_exists": ("Subheadings (H2)", HIGH, LO,
    "Subheadings break the page into scannable sections. Both readers and AI assistants use them to find the part of the page that answers their question.",
    "Add descriptive H2 headings for each major section."),
"heading_hierarchy": ("Heading structure order", MEDIUM, LO,
    "Skipping levels (H1 straight to H4) breaks the document outline that screen readers and crawlers rely on to understand structure.",
    "Nest headings in order: H1, then H2, then H3 under each H2."),
"word_count": ("Content depth", HIGH, ME,
    "Very thin pages rarely rank against competitors and give AI assistants nothing worth quoting. Depth is not about padding — it is about actually answering the questions a buyer has.",
    "Expand to at least 600-800 words of genuinely useful detail on service pages."),
"readability_score": ("Readability", MEDIUM, ME,
    "Dense, complex writing loses readers before they reach the enquiry form, and scores badly on the clarity signals AI answer engines favour.",
    "Aim for a readability score of 60+: shorter sentences, plainer words, more white space."),
"sentence_length": ("Sentence length", MEDIUM, LO,
    "Long sentences are hard to skim on a phone and hard for AI to extract as a clean quotable answer.",
    "Break sentences over 20 words into two. Target under 25% long sentences."),
"img_alt": ("Image ALT text", HIGH, LO,
    "ALT text is how blind users and search engines know what an image shows. It is also a legal accessibility expectation and a source of image-search traffic.",
    "Add short, literal ALT text describing each meaningful image."),
"img_dimensions": ("Image width and height", MEDIUM, LO,
    "Without declared dimensions the browser does not reserve space, so content jumps around as images load. That layout shift is a ranking factor and a common cause of mis-taps on mobile.",
    "Add explicit width and height attributes to every img tag."),
"img_lazy": ("Image lazy loading", MEDIUM, LO,
    "Loading off-screen images upfront wastes mobile data and delays the content the visitor actually came for.",
    'Add loading="lazy" to images below the fold.'),
"img_modern_format": ("Modern image formats", MEDIUM, ME,
    "WebP and AVIF are typically 30-50% smaller than JPEG or PNG at the same quality, which directly improves load speed on mobile data.",
    "Convert photos to WebP or AVIF and keep SVG for logos and icons."),
"internal_links": ("Internal linking", HIGH, LO,
    "Links between your own pages spread ranking strength around the site and guide visitors from reading to enquiring. Orphan pages rarely rank.",
    "Link each page to the related services and to the contact or quote page."),
"external_links": ("Outbound links", LOW, LO,
    "Citing credible external sources is a trust signal for both search engines and AI answer engines.",
    "Link out to authoritative sources where you reference facts or standards."),
"empty_hrefs": ("Empty links", MEDIUM, LO,
    "Links with no destination frustrate visitors, waste crawl budget and often indicate broken navigation code.",
    'Remove empty href="" or href="#" links, or give them real destinations.'),
"descriptive_anchors": ("Link wording", MEDIUM, LO,
    "'Click here' and 'read more' tell search engines and screen readers nothing about the destination, wasting a free relevance signal.",
    "Rewrite link text to describe the destination, e.g. 'view our roofing services'."),
"broken_links": ("Broken links", HIGH, LO,
    "Dead links send paying visitors to error pages and signal a neglected site to search engines.",
    "Fix or remove links returning 404 errors."),
"nofollow_ratio": ("Nofollow link ratio", LOW, LO,
    "Excessive nofollow on internal links blocks ranking strength from flowing through your own site.",
    "Remove rel=nofollow from internal links."),
"first_person": ("First-hand experience signals", MEDIUM, LO,
    "Google's E-E-A-T guidance rewards content that shows genuine first-hand experience rather than generic copy that could describe any business.",
    "Write from real experience: what you did, what you found, what you recommend."),
"transition_words": ("Transition words", LOW, LO,
    "Connecting words make copy flow and easier to follow, which helps readers stay on the page.",
    "Use linking words such as however, because and as a result in roughly 20% of sentences."),
"img_responsive": ("Responsive images", MEDIUM, ME,
    "Without srcset, phones download full desktop-sized images, burning mobile data and slowing the page badly on 3G/4G.",
    "Add srcset and sizes so each device downloads an appropriately sized image."),
"h1_length": ("H1 length", MEDIUM, LO,
    "A very short headline carries almost no keyword or persuasive information; a very long one dilutes the page's topic.",
    "Write an H1 of roughly 20-70 characters stating the offer clearly."),
"excessive_links": ("Links per page", LOW, LO,
    "Hundreds of links on one page dilute the ranking value each one passes and overwhelm visitors.",
    "Keep to the links that genuinely help the visitor take the next step."),
"section_depth": ("Section depth", MEDIUM, ME,
    "Sections with a heading but only a line or two of text read as filler and give AI nothing citable.",
    "Give each H2 section at least 80-120 words of substance."),

# ── SEO :: social ────────────────────────────────────────────────────────────
"og_title": ("Social share title", HIGH, LO,
    "This is the headline that appears when your link is pasted into WhatsApp, Facebook or LinkedIn. Without it the preview falls back to a URL, which almost nobody clicks.",
    'Add <meta property="og:title" content="...">.'),
"og_desc": ("Social share description", MEDIUM, LO,
    "The supporting line in a link preview. Blank previews get far fewer clicks when your link is shared.",
    'Add <meta property="og:description" content="...">.'),
"og_image": ("Social share image", HIGH, LO,
    "The picture in a shared link preview. A link with an image gets dramatically more engagement than a bare text link — this matters every time a client shares you in a WhatsApp group.",
    'Add <meta property="og:image" content="https://..."> at 1200x630px.'),
"og_url": ("Social canonical URL", LOW, LO,
    "Keeps shares and engagement counts consolidated on one canonical address.",
    'Add <meta property="og:url" content="https://...">.'),
"og_type": ("Open Graph type", LOW, LO,
    "Tells platforms whether this is a website, article or product so they render the right preview layout.",
    'Add <meta property="og:type" content="website">.'),
"og_site_name": ("Open Graph site name", LOW, LO,
    "Shows your brand name above the preview, adding recognition to every share.",
    'Add <meta property="og:site_name" content="Your Brand">.'),
"twitter_card": ("X/Twitter card type", LOW, LO,
    "Controls whether X renders a large image card or a small one. Large cards get noticeably more clicks.",
    'Add <meta name="twitter:card" content="summary_large_image">.'),
"twitter_title": ("X/Twitter title", LOW, LO,
    "Headline used specifically by X when your link is posted.",
    'Add <meta name="twitter:title" content="...">.'),
"twitter_desc": ("X/Twitter description", LOW, LO,
    "Supporting line for X link previews.",
    'Add <meta name="twitter:description" content="...">.'),
"twitter_image": ("X/Twitter image", LOW, LO,
    "Preview image for X. Without it the post renders as plain text and gets scrolled past.",
    'Add <meta name="twitter:image" content="https://...">.'),
"og_image_url": ("Absolute social image URL", MEDIUM, LO,
    "Relative image paths break in link previews because the sharing platform cannot resolve them, leaving a blank card.",
    "Use the full https:// URL for og:image."),
"og_canonical_match": ("Social and canonical URL match", LOW, LO,
    "Mismatched URLs split social signals and can cause previews to point at the wrong page.",
    "Make og:url identical to the canonical URL."),

# ── SEO :: technical ─────────────────────────────────────────────────────────
"https": ("HTTPS encryption", CRITICAL, LO,
    "Browsers label non-HTTPS sites 'Not secure' in the address bar, which destroys trust at the exact moment someone is deciding whether to enquire. It is also a confirmed ranking factor and a POPIA expectation for any site collecting personal details.",
    "Install a TLS certificate and force all traffic to https://."),
"canonical": ("Canonical tag", HIGH, LO,
    "Tells search engines which version of a page is the real one. Without it, duplicate URLs compete with each other and split ranking strength.",
    'Add <link rel="canonical" href="https://..."> to every page.'),
"canonical_self": ("Self-referencing canonical", HIGH, LO,
    "A canonical pointing at a different page tells Google to ignore this page entirely — a silent way to lose rankings.",
    "Point each page's canonical at its own URL unless it is a genuine duplicate."),
"favicon": ("Favicon", LOW, LO,
    "The little icon on the browser tab and in search results. Its absence reads as an unfinished site.",
    "Add a favicon.ico and a 512px PNG icon."),
"apple_touch_icon": ("Apple touch icon", LOW, LO,
    "The icon used when someone saves your site to an iPhone home screen.",
    'Add <link rel="apple-touch-icon" href="/apple-touch-icon.png"> at 180x180px.'),
"compression": ("Text compression", HIGH, LO,
    "Gzip or Brotli compression typically cuts page transfer size by 70%, which is the single cheapest speed win on a slow mobile connection.",
    "Enable Brotli or gzip at the server or CDN."),
"url_length": ("URL length", LOW, LO,
    "Long, parameter-stuffed URLs get truncated in results and are awkward to share verbally or in print.",
    "Keep URLs short and readable."),
"url_hyphens": ("URL word separators", MEDIUM, LO,
    "Search engines read hyphens as word breaks but not underscores, so under_scored URLs hide your keywords.",
    "Use hyphens between words in URLs."),
"hreflang": ("Hreflang tags", LOW, ME,
    "Only relevant if you serve several countries or languages — it stops the wrong regional version showing to the wrong audience.",
    "Add hreflang tags only if you run multi-language or multi-country versions."),
"deprecated_html": ("Deprecated HTML", LOW, LO,
    "Obsolete tags signal an ageing codebase and can render inconsistently in modern browsers.",
    "Replace deprecated tags with current HTML5 and CSS."),
"text_html_ratio": ("Text to code ratio", MEDIUM, ME,
    "When a page is mostly framework code with very little readable text, search engines and AI assistants have little to actually index or quote.",
    "Add real written content and trim unused scripts and markup."),
"html_doctype": ("HTML doctype", MEDIUM, LO,
    "Without a doctype, browsers fall back to quirks mode and the layout can break unpredictably.",
    "Add <!DOCTYPE html> as the first line."),
"mixed_content": ("Mixed content", HIGH, LO,
    "An HTTPS page loading images or scripts over plain HTTP triggers browser security warnings and can leave parts of the page blank.",
    "Serve every asset over https://."),
"robots_txt": ("robots.txt file", CRITICAL, LO,
    "This file controls crawler access. A wrong line here can block your entire site from Google — it is the most damaging one-line mistake in SEO.",
    "Publish a robots.txt that allows crawling of your public pages."),
"robots_txt_sitemap": ("Sitemap reference in robots.txt", MEDIUM, LO,
    "Pointing crawlers at your sitemap from robots.txt speeds up discovery of new and updated pages.",
    "Add a Sitemap: https://yoursite/sitemap.xml line to robots.txt."),
"ai_crawlers_blocked": ("AI crawler access", HIGH, LO,
    "If GPTBot, ClaudeBot and PerplexityBot are blocked, your business simply cannot be recommended by AI assistants — an increasingly common way buyers now shortlist suppliers.",
    "Allow AI crawlers in robots.txt unless you have a deliberate reason not to."),
"sitemap_xml": ("XML sitemap", HIGH, LO,
    "A sitemap is the list of pages you are asking Google to index. Without one, deeper pages can go undiscovered for months.",
    "Publish sitemap.xml and submit it in Google Search Console."),
"sitemap_urls": ("Sitemap coverage", MEDIUM, LO,
    "A sitemap missing key pages means those pages rely on luck to be found.",
    "Include every page you want ranked, and nothing you do not."),
"web_manifest": ("Web app manifest", LOW, LO,
    "Lets visitors install the site to their home screen and controls how it looks when they do.",
    "Add a manifest.json with name, icons and theme colour."),
"nosnippet_blocking": ("Snippet blocking", HIGH, LO,
    "nosnippet directives stop Google and AI assistants from showing any preview of your content, which crushes click-through.",
    "Remove nosnippet and data-nosnippet unless there is a legal reason for them."),
"rss_feed": ("RSS/Atom feed", LOW, LO,
    "Feeds help aggregators and AI services pick up new content quickly. Minor, but free if the platform supports it.",
    "Expose an RSS feed and link it from <head>."),
"indexnow": ("IndexNow", LOW, LO,
    "Pushes new pages to Bing and Yandex instantly. Google does not use it, so the impact is limited.",
    "Optional: enable IndexNow if your platform supports it."),

# ── SEO :: performance ───────────────────────────────────────────────────────
"inline_css": ("Inline CSS volume", LOW, ME,
    "Large blocks of inline styles bloat every page load because they cannot be cached separately.",
    "Move bulk styles to an external cached stylesheet."),
"inline_js": ("Inline JavaScript volume", MEDIUM, ME,
    "Inline scripts are re-downloaded with every page instead of being cached once, and they push back the moment the page becomes usable.",
    "Move scripts to external files that browsers can cache."),
"script_defer": ("Render-blocking scripts", HIGH, LO,
    "Scripts without defer or async freeze rendering: the visitor stares at a blank screen while they download. On mobile data this is where impatient visitors leave.",
    "Add defer (or async) to script tags that are not needed immediately."),
"font_preload": ("Font preloading", MEDIUM, LO,
    "Without preloading, text is invisible or swaps font mid-read while the browser fetches the file, which looks broken.",
    "Preload the primary font file and preconnect to the font host."),
"cache_control": ("Browser caching", HIGH, LO,
    "Correct cache headers mean returning visitors re-download almost nothing, making the second visit feel instant.",
    "Set long max-age with immutable on static assets."),
"resource_hints": ("Resource hints", MEDIUM, LO,
    "preconnect and dns-prefetch let the browser start connecting to third-party domains early instead of waiting.",
    "Add preconnect for fonts, analytics and any critical third-party host."),
"dom_size": ("Page complexity", MEDIUM, HI,
    "Very large DOMs make phones sluggish to scroll and interact with, hurting both experience and Core Web Vitals.",
    "Simplify markup and avoid rendering huge lists all at once."),
"render_blocking": ("Render-blocking resources in head", HIGH, LO,
    "Every blocking resource in the head delays first paint — the moment the visitor sees anything at all.",
    "Defer non-critical scripts and inline only critical CSS."),
"third_party_scripts": ("Third-party scripts", MEDIUM, ME,
    "Every extra tracking or chat script adds load time and another privacy disclosure obligation under POPIA.",
    "Audit third-party scripts and remove what is not earning its place."),

# ── SEO :: security ──────────────────────────────────────────────────────────
"hsts": ("HSTS header", HIGH, LO,
    "Forces browsers to use HTTPS for every future visit, closing the window where a visitor could be downgraded to an insecure connection on public Wi-Fi.",
    "Send Strict-Transport-Security with a max-age of at least one year."),
"x_content_type": ("MIME sniffing protection", MEDIUM, LO,
    "Stops browsers guessing file types, a common route for turning an uploaded file into executable script.",
    "Send X-Content-Type-Options: nosniff."),
"csp": ("Content Security Policy", HIGH, ME,
    "A CSP is the main defence against injected scripts stealing form data — directly relevant wherever a site collects personal information.",
    "Add a Content-Security-Policy header, starting in report-only mode."),
"link_noopener": ("External link safety", MEDIUM, LO,
    'Links opening in a new tab without rel="noopener" let the destination page manipulate your original tab.',
    'Add rel="noopener noreferrer" to every target="_blank" link.'),
"referrer_policy": ("Referrer policy", LOW, LO,
    "Controls how much of your URL is leaked to sites your visitors click through to.",
    "Send Referrer-Policy: strict-origin-when-cross-origin."),
"permissions_policy": ("Permissions policy", LOW, LO,
    "Explicitly denies camera, microphone and location access to embedded content that has no business asking.",
    "Send a Permissions-Policy header denying unused features."),
"iframe_sandbox": ("Iframe sandboxing", MEDIUM, LO,
    "An unsandboxed iframe runs third-party code with more privileges than it needs on your domain.",
    "Add the sandbox attribute with only the permissions the embed truly requires."),

# ── SEO :: trust ─────────────────────────────────────────────────────────────
"trust_about": ("About page", HIGH, LO,
    "Buyers check who they are dealing with before parting with money, and Google's quality guidance explicitly looks for evidence of a real organisation behind the site.",
    "Publish an About page with real people, real history and real photos."),
"trust_contact": ("Contact details", CRITICAL, LO,
    "A visible phone number, email and address is the highest-converting trust element on a small business site — and its absence reads as a scam risk.",
    "Publish full contact details and link them from every page."),
"trust_privacy": ("Privacy policy", HIGH, LO,
    "Legally expected under POPIA wherever you collect personal information through a form, and a standard trust check for buyers.",
    "Publish a privacy policy covering what you collect, why, and how long you keep it."),
"trust_terms": ("Terms of service", MEDIUM, LO,
    "Sets out what you are and are not committing to, and is a routine trust signal for search quality raters.",
    "Publish terms of service and link them in the footer."),
"author_byline": ("Author byline", MEDIUM, LO,
    "Named authors with credentials are a core E-E-A-T signal and strongly influence whether AI assistants trust and cite the page.",
    "Add a named author with a short credential line to articles."),

# ── SEO :: schema ────────────────────────────────────────────────────────────
"jsonld": ("Structured data (JSON-LD)", HIGH, ME,
    "Structured data is machine-readable fact sheet for your business: hours, address, services, reviews. It powers rich results and is how AI assistants confirm who you are.",
    "Add JSON-LD for Organization or LocalBusiness on every page."),
"schema_types": ("Schema coverage", MEDIUM, ME,
    "The more accurately your schema describes what you are, the better search engines can match you to relevant queries.",
    "Add the schema types matching your business: LocalBusiness, Service, FAQPage, Product."),
"structured_data_valid": ("Structured data validity", HIGH, LO,
    "Broken JSON-LD is silently ignored, so you get none of the benefit while believing it is working.",
    "Validate every block in Google's Rich Results Test and fix syntax errors."),
"schema_required_props": ("Required schema properties", MEDIUM, LO,
    "Schema missing its required fields is discarded by Google, again silently.",
    "Fill in all required properties for each schema type you use."),
"org_logo": ("Organisation logo in schema", MEDIUM, LO,
    "Gives Google a definitive logo for knowledge panels and brand results instead of guessing from the page.",
    "Add a logo property with an absolute URL to your Organization schema."),

# ── SEO :: accessibility ─────────────────────────────────────────────────────
"viewport_zoom": ("Pinch zoom allowed", MEDIUM, LO,
    "Blocking zoom locks out anyone with less than perfect eyesight, and it is an explicit WCAG failure.",
    "Remove user-scalable=no and maximum-scale from the viewport tag."),
"aria_landmarks": ("ARIA landmarks", MEDIUM, LO,
    "Landmarks let screen reader users jump straight to the main content instead of hearing the whole menu each time.",
    "Use semantic <main>, <nav>, <header>, <footer> elements and a skip link."),
"form_labels": ("Form field labels", HIGH, LO,
    "Unlabelled fields are unusable with a screen reader and confusing for everyone once the placeholder disappears — a direct cause of abandoned enquiry forms.",
    "Give every input a matching <label> or aria-label."),
"duplicate_ids": ("Duplicate element IDs", LOW, LO,
    "Repeated IDs break JavaScript targeting and label associations in unpredictable ways.",
    "Make every id attribute unique on the page."),

# ── AEO :: discoverability ───────────────────────────────────────────────────
"aeo_structured_data": ("Structured data for AI", HIGH, ME,
    "AI assistants read structured data first because it states facts unambiguously. Without it, an assistant has to infer what you do from prose and often gets it wrong or skips you.",
    "Add JSON-LD describing your organisation, services and location."),
"aeo_html_content": ("Readable HTML content", CRITICAL, ME,
    "If the words only appear after JavaScript runs, many AI crawlers never see them. Content that is not in the HTML effectively does not exist to them.",
    "Server-render key content so it is present in the raw HTML."),
"aeo_clean_url": ("Clean URL structure", LOW, LO,
    "Readable URLs help AI systems understand page topic and hierarchy before they even read the content.",
    "Use short, descriptive, lowercase URLs with hyphens."),
"aeo_semantic_html": ("Semantic HTML elements", MEDIUM, ME,
    "Tags like <article>, <section> and <main> tell machines which part of the page is the actual content versus navigation and footer clutter.",
    "Replace generic <div> wrappers with semantic HTML5 elements."),
"aeo_segmentation": ("Content segmentation", MEDIUM, LO,
    "Clearly separated sections let an assistant lift exactly the relevant part of your page as an answer instead of ignoring the page as one undifferentiated block.",
    "Break content into labelled sections with descriptive headings."),
"aeo_topic_signals": ("Topic clarity signals", MEDIUM, LO,
    "Consistent description and social metadata gives AI systems a confident read on what this page is about.",
    "Keep meta description and og:description present and aligned."),
"aeo_named_entities": ("Named entities", MEDIUM, ME,
    "Named people, places, brands and products are what AI systems anchor understanding to. Vague copy with no proper nouns is hard to categorise and easy to skip.",
    "Name your service areas, product names, partners and team explicitly."),
"aeo_internal_links": ("Internal topic clusters", MEDIUM, LO,
    "Interlinked pages on a theme signal genuine depth of expertise rather than a single thin page.",
    "Link related pages together around each core service topic."),
"aeo_definition_lists": ("Definition lists", LOW, LO,
    "Definition lists present term-and-meaning pairs in a format AI can extract cleanly, useful for glossaries and spec sheets.",
    "Use <dl>, <dt> and <dd> for term/definition content."),
"aeo_code_blocks": ("Code blocks", LOW, LO,
    "Only relevant for technical content — properly marked code is extracted accurately rather than mangled.",
    "Wrap code samples in <pre> and <code>. Ignore if not a technical site."),
"aeo_ai_robots": ("AI robots directives", HIGH, LO,
    "Directives that block AI crawlers remove you from AI-generated recommendations entirely.",
    "Remove AI-blocking meta directives unless the exclusion is deliberate."),
"aeo_llms_txt": ("llms.txt file", LOW, LO,
    "An emerging convention for giving AI systems a curated summary of your site. Google has confirmed it has no effect on Search, so treat this as optional and forward-looking.",
    "Optionally publish /llms.txt summarising your key pages."),
"aeo_ai_crawlers": ("AI crawler allowlist", HIGH, LO,
    "Each blocked AI crawler is one more assistant that can never mention your business when a buyer asks for a recommendation.",
    "Allow GPTBot, ClaudeBot, PerplexityBot and similar in robots.txt."),
"aeo_video": ("Video content", LOW, HI,
    "Video keeps visitors on the page longer and gives AI additional media signals, though transcripts matter more than the video itself.",
    "Embed relevant video and publish a text transcript alongside it."),

# ── AEO :: structure ─────────────────────────────────────────────────────────
"aeo_faq": ("FAQ / Q&A content", HIGH, ME,
    "Real customer questions with direct answers are the single most extractable content format for AI assistants. Note the schema markup is now optional, but the Q&A content itself matters more than ever.",
    "Add a section answering the six or eight questions customers actually ask."),
"aeo_question_headings": ("Question-style headings", HIGH, LO,
    "Headings phrased as questions match how people actually type and speak their searches, making your section the obvious answer to lift.",
    "Rewrite some H2s as the question a customer would ask."),
"aeo_lists": ("Bullet and numbered lists", MEDIUM, LO,
    "Lists are the format AI most reliably extracts and reproduces. A wall of prose is far less likely to be quoted.",
    "Convert dense paragraphs into bulleted lists where the content is a set of items."),
"aeo_tables": ("Data tables", MEDIUM, ME,
    "Tables let AI compare your options, pricing or specs against competitors and cite the comparison directly.",
    "Present comparable data in a proper HTML <table>."),
"aeo_direct_answers": ("Direct answer paragraphs", HIGH, LO,
    "Answering the heading's question in the first sentence beneath it is what makes a passage quotable. Burying the answer three paragraphs down loses the citation.",
    "Put a concise, complete answer immediately after each heading."),
"aeo_numbered_steps": ("Step-by-step content", MEDIUM, ME,
    "Numbered steps are the preferred source for 'how do I...' answers, which is a large share of AI queries.",
    "Turn processes into numbered <ol> steps."),
"aeo_short_sentences": ("Short sentences", MEDIUM, LO,
    "Short sentences survive extraction intact; long ones get truncated or paraphrased inaccurately.",
    "Aim for a majority of sentences under 20 words."),
"aeo_concise_paragraphs": ("Concise paragraphs", MEDIUM, LO,
    "Tight paragraphs of 20-80 words are the natural unit an assistant lifts as an answer.",
    "Split long paragraphs so each covers one idea."),
"aeo_key_value": ("Key-value formatting", LOW, LO,
    "Explicit 'Label: value' pairs are read as structured facts rather than prose.",
    "Format specs and details as bold label followed by value."),
"aeo_section_depth": ("AI section depth", MEDIUM, ME,
    "Sections too thin to stand alone are not worth citing; the assistant needs a self-contained passage.",
    "Give each section enough depth to answer its heading fully on its own."),
"aeo_toc": ("Table of contents", LOW, LO,
    "Jump links map the page structure for both readers and machines on long pages.",
    "Add an anchor-linked contents list to long pages."),
"aeo_collapsible": ("Expandable Q&A blocks", LOW, LO,
    "<details>/<summary> pairs keep long FAQ pages tidy while staying fully readable to crawlers.",
    "Use <details> and <summary> for expandable questions."),

# ── AEO :: citation ──────────────────────────────────────────────────────────
"aeo_author": ("Author identity", HIGH, LO,
    "AI systems weight content by who stands behind it. Anonymous content is systematically deprioritised against a named expert saying the same thing.",
    "Attribute content to a named person with a short credential line."),
"aeo_date": ("Publication date", HIGH, LO,
    "Undated content is treated as possibly stale, and assistants prefer recent sources when recommending suppliers.",
    "Show a visible published date and add datePublished to schema."),
"aeo_statistics": ("Statistics and data", HIGH, ME,
    "Specific figures are the most-cited content type in AI answers, because a number is verifiable in a way an adjective is not.",
    "Replace vague claims with concrete numbers, with sources."),
"aeo_org_schema": ("Organisation schema", HIGH, LO,
    "This is how an AI confirms your brand is a real, identifiable entity rather than an unknown domain.",
    "Add Organization or LocalBusiness JSON-LD with name, logo, URL and contact."),
"aeo_eeat": ("E-E-A-T signals", HIGH, ME,
    "Experience, expertise, authority and trust are the criteria both Google and AI systems use to decide whether to rely on you.",
    "Show credentials, real experience, contact details, policies and named authors."),
"aeo_citations": ("Source citations", MEDIUM, ME,
    "Content that cites its sources is treated as more reliable, and gets quoted more often as a result.",
    "Reference and link the studies, standards or data you rely on."),
"aeo_authority_links": ("Links to authoritative sources", MEDIUM, LO,
    "Linking to recognised authorities associates your page with them in the eyes of AI ranking systems.",
    "Link to standards bodies, official documentation and reputable research."),
"aeo_freshness": ("Content freshness", HIGH, LO,
    "Stale year references make an assistant assume the whole page is out of date and prefer a competitor.",
    "Update and re-date content at least annually; remove outdated year references."),
"aeo_topic_focus": ("Topic focus", MEDIUM, LO,
    "When the title's keywords never appear in the body, AI cannot confirm the page delivers what it promises.",
    "Make sure the body actually covers the terms in the title."),
"aeo_answer_box": ("Answer-ready paragraphs", HIGH, LO,
    "Self-contained paragraphs that answer a question in isolation are exactly what gets lifted into an AI answer with attribution.",
    "Write standalone answer paragraphs directly under question headings."),
"aeo_last_modified": ("Last-modified signal", MEDIUM, LO,
    "Freshness headers and dateModified tell crawlers the page is maintained rather than abandoned.",
    "Send a Last-Modified header and include dateModified in schema."),
"aeo_sameas_links": ("sameAs brand links", MEDIUM, LO,
    "Linking your schema to your verified social and directory profiles proves you are one consistent entity across the web.",
    "Add sameAs URLs for LinkedIn, Facebook, Google Business Profile and similar."),
"aeo_brand_consistency": ("Brand name consistency", MEDIUM, LO,
    "Different brand spellings across title, social tags and schema fragment your entity, weakening every mention.",
    "Use exactly the same brand name in title, OG tags and schema."),
"aeo_update_recency": ("Recent updates", HIGH, LO,
    "Recently updated pages are strongly preferred by AI engines, which favour current information when giving recommendations.",
    "Review and genuinely update key pages at least quarterly."),
"aeo_data_attribution": ("Data attribution", MEDIUM, LO,
    "Unattributed statistics are treated as unverifiable and are dropped rather than cited.",
    "Name and link the source next to every statistic you quote."),
"aeo_entity_consistency": ("Entity consistency", MEDIUM, LO,
    "Consistent naming through the content reinforces which entity the page is about.",
    "Refer to the brand by the same name throughout the copy."),

# ── AEO :: voice ─────────────────────────────────────────────────────────────
"aeo_speakable": ("Speakable schema", LOW, LO,
    "Marks the sections best suited to being read aloud by voice assistants. Still a limited Google beta, so low impact today.",
    "Optional: add speakable schema to the summary section."),
"aeo_conversational": ("Conversational language", MEDIUM, LO,
    "People type and speak queries in natural language. Copy written the way customers actually talk matches more queries.",
    "Write the way you would explain it to a customer on the phone."),
"aeo_snippet_ready": ("Snippet-ready opening", HIGH, LO,
    "The first paragraph is the most commonly extracted passage on any page. If it is a marketing flourish rather than an answer, the extraction opportunity is wasted.",
    "Open with a 20-60 word paragraph that plainly states what this is and who it is for."),
"aeo_search_action": ("SearchAction schema", LOW, LO,
    "Historically powered the sitelinks search box, which Google retired in 2024. Harmless but no longer useful.",
    "Optional: leave as is, or remove for cleaner markup."),
"aeo_reading_level": ("Reading level", MEDIUM, LO,
    "Complex sentence structure raises the chance an assistant paraphrases you inaccurately, or skips you for a clearer source.",
    "Simplify to around 15-20 words per sentence."),
"aeo_active_voice": ("Active voice", LOW, LO,
    "Active sentences state clearly who does what, which extracts more cleanly than passive constructions.",
    "Rewrite passive sentences into active ones."),
"aeo_pronoun_density": ("Reader-focused language", LOW, LO,
    "Addressing the reader as 'you' converts better and reads as genuinely helpful content rather than a corporate brochure.",
    "Write to the customer using 'you' and 'your'."),
"aeo_summary": ("Key takeaways summary", HIGH, LO,
    "A short summary block is one of the most reliably extracted elements on a page and lets you control exactly what an assistant repeats about you.",
    "Add a Key Takeaways or In Short block near the top of long pages."),
"aeo_heading_density": ("Heading density", MEDIUM, LO,
    "Too few headings across long content leaves AI unable to locate the relevant passage.",
    "Add a heading roughly every 200-300 words."),
"aeo_qa_blocks": ("Q&A blocks", HIGH, ME,
    "Question heading followed immediately by a direct answer is the highest-yield structure for AI citation.",
    "Convert key sections into question-and-answer pairs."),

# ── GEO :: overview ──────────────────────────────────────────────────────────
"geo_definitions": ("Definition-style content", HIGH, LO,
    "'X is...' sentences are the classic featured-snippet and AI-summary trigger, because they answer the question completely in one line.",
    "Define your core terms and services in a single clean sentence each."),
"geo_paa_format": ("People-Also-Ask formatting", HIGH, LO,
    "Question-formatted headings match the related-questions boxes that increasingly occupy the top of results and feed AI Overviews.",
    "Add headings phrased as the questions customers actually ask."),
"geo_freshness": ("Freshness signals", HIGH, LO,
    "Generative engines heavily prefer current sources, particularly for pricing, availability and regulation.",
    "Date your content and keep the facts current."),
"geo_content_depth": ("Content depth for AI Overview", HIGH, ME,
    "Thin pages are rarely used as an AI Overview source because there is not enough substance to synthesise from.",
    "Expand to comprehensive coverage: aim for 1000+ words across clearly distinct sections."),
"geo_intent_clarity": ("Search intent clarity", HIGH, LO,
    "When the title and H1 disagree, AI cannot confidently match the page to a query and will pick a clearer competitor.",
    "Align title and H1 around the same clearly stated topic."),
"geo_structured_answers": ("Structured answers", MEDIUM, ME,
    "Step-by-step and structured formats are what generative engines reach for when composing procedural answers.",
    "Add numbered guides for the processes customers ask about."),
"geo_hierarchy_depth": ("Heading hierarchy depth", MEDIUM, LO,
    "A proper H2/H3 hierarchy shows genuine subtopic coverage rather than a flat brochure page.",
    "Use H3 subheadings under each H2 to cover subtopics."),
"geo_paragraph_length": ("Paragraph length", MEDIUM, LO,
    "Paragraphs of 20-80 words are the ideal extraction unit — longer ones get truncated, shorter ones lack context.",
    "Reshape paragraphs to sit in the 20-80 word range."),
"geo_content_length": ("Overall content length", HIGH, ME,
    "There must be enough substance for a generative engine to have something worth summarising.",
    "Build key pages out to at least 800-1000 words of real information."),
"geo_first_200_words": ("First 200 words", HIGH, LO,
    "AI weights the opening of a page most heavily. If your core topic terms are missing there, the page can be passed over before the good part is reached.",
    "Work the main topic and service terms naturally into the opening paragraphs."),
"geo_featured_snippet": ("Featured snippet format", HIGH, ME,
    "Combining a crisp definition with a supporting list is the format most often promoted into snippets and AI summaries.",
    "Pair a one-sentence definition with a short bulleted list."),
"geo_comprehensiveness": ("Question coverage", HIGH, ME,
    "Covering what, why, how, when, where and who signals complete coverage of a topic, which is what generative engines look for in a primary source.",
    "Add sections answering each of the main question types for your topic."),
"geo_boilerplate": ("Content to boilerplate ratio", MEDIUM, ME,
    "When navigation, banners and footers dominate the page, the actual content is diluted and harder to isolate.",
    "Increase real content and trim repeated page furniture."),
"geo_no_popup_walls": ("Intrusive interstitials", HIGH, LO,
    "Popups and paywalls covering content are an explicit Google demotion factor on mobile and block AI extraction.",
    "Remove full-screen interstitials, especially on mobile entry."),
"geo_passage_citability": ("Citable passages", CRITICAL, ME,
    "This is the core of generative visibility: self-contained passages that make sense quoted on their own. Content that only makes sense in the context of the whole page rarely gets cited.",
    "Write 120-180 word sections that open with the answer and stand alone."),

# ── GEO :: authority ─────────────────────────────────────────────────────────
"geo_author_schema": ("Author schema", HIGH, LO,
    "Machine-readable authorship is a direct trust input for generative engines deciding whether to rely on your page.",
    "Add author with name and credentials to your Article or Organization schema."),
"geo_citations": ("Citations in content", MEDIUM, ME,
    "Pages that cite sources are treated as more reliable and are themselves cited more often.",
    "Reference and link your sources inline."),
"geo_trust": ("Trust signals", HIGH, LO,
    "Contact details, policies, credentials and real addresses are what separate a legitimate supplier from an anonymous domain in an AI's assessment.",
    "Publish address, phone, registration details, policies and team credentials."),
"geo_brand": ("Brand consistency", MEDIUM, LO,
    "Consistent brand identity across metadata and schema strengthens entity recognition.",
    "Keep brand naming identical across OG tags and schema."),
"geo_original": ("Original data and research", HIGH, HI,
    "Original data is the most powerful citation magnet there is — nobody else can be the source for your own numbers.",
    "Publish your own findings: survey results, project statistics, before-and-after data."),
"geo_expert_quotes": ("Expert quotes", MEDIUM, ME,
    "Named expert commentary adds authority that generic copy cannot, and gives assistants an attributable line to quote.",
    "Include short quotes from named, credentialled people."),
"geo_case_study": ("Case studies and examples", HIGH, ME,
    "Concrete examples with real outcomes are heavily favoured over generic claims, and they are what buyers ask AI for by name.",
    "Publish specific client examples with the problem, action and measurable result."),
"geo_industry_terms": ("Industry terminology", MEDIUM, LO,
    "Correct domain vocabulary signals genuine expertise and helps AI classify your content into the right subject area.",
    "Use the proper technical terms your industry actually uses."),
"geo_authority_links": ("Authoritative outbound links", MEDIUM, LO,
    "Referencing recognised authorities helps generative engines place your content in a trusted neighbourhood.",
    "Link to standards bodies, regulators or primary documentation where relevant."),
"geo_source_diversity": ("Source diversity", LOW, LO,
    "Drawing on a range of sources reads as balanced research rather than a single rehashed article.",
    "Reference several distinct, credible domains."),
"geo_statistics_density": ("Statistics density", HIGH, ME,
    "Adding statistics is one of the few tactics with published research behind it showing a measurable lift in generative-engine visibility.",
    "Add specific figures with units and sources throughout the content."),
"geo_author_credentials": ("Author credentials", HIGH, LO,
    "An author name without credentials carries little weight; qualifications and experience are what make the attribution meaningful.",
    "State the author's qualifications and years of relevant experience."),
"geo_knowledge_graph": ("Entity disambiguation", MEDIUM, LO,
    "sameAs links to authoritative profiles help AI tell your business apart from similarly named ones. Note this alone does not create a Knowledge Panel.",
    "Add sameAs links to your verified profiles and listings."),
"geo_keyword_stuffing": ("Keyword stuffing", HIGH, LO,
    "Repetitive keyword stuffing is detected and penalised, and it makes copy unpleasant to read for the humans you actually want.",
    "Write naturally; remove repeated keyword padding."),
"geo_bot_access": ("AI bot access", CRITICAL, LO,
    "If GPTBot, ClaudeBot and PerplexityBot cannot fetch the page, no amount of optimisation will get you mentioned in AI answers.",
    "Confirm AI crawlers are allowed in robots.txt and not blocked at the firewall or WAF."),
"geo_ai_discovery": ("AI discovery files", LOW, LO,
    "Emerging convention for exposing a machine-readable summary of your site. Optional and unproven, but cheap to add.",
    "Optionally publish /llms.txt or an /ai/summary.json."),

# ── GEO :: format ────────────────────────────────────────────────────────────
"geo_faq_schema": ("FAQ schema", LOW, LO,
    "Google retired FAQ rich results in May 2026, so the markup itself now does little. The underlying Q&A content still matters a great deal.",
    "Prioritise real Q&A content; the schema is optional."),
"geo_howto_schema": ("HowTo schema", LOW, LO,
    "HowTo rich results were deprecated in 2023, but step-by-step content still performs strongly for AI answers.",
    "Focus on genuine step-by-step content rather than the markup."),
"geo_comparison": ("Comparison content", HIGH, ME,
    "'X vs Y' content is disproportionately used when AI is asked to recommend between options — exactly the moment a buyer is choosing a supplier.",
    "Add honest comparison sections covering your options and alternatives."),
"geo_summary": ("Summary / TL;DR", HIGH, LO,
    "A summary block is prime extraction material and lets you dictate the sentence an assistant repeats about you.",
    "Add a Key Takeaways or TL;DR block near the top."),
"geo_visual": ("Visual content with ALT", MEDIUM, LO,
    "Described images give AI extra context and make the page accessible at the same time.",
    "Add meaningful images with descriptive ALT text."),
"geo_breadcrumb": ("Breadcrumb schema", MEDIUM, LO,
    "Breadcrumbs show where the page sits in your site's structure, which helps AI understand context and shows in search results.",
    "Add BreadcrumbList JSON-LD and a visible breadcrumb trail."),
"geo_data_viz": ("Data tables and charts", MEDIUM, ME,
    "Structured data presentation is easier for AI to interpret and cite accurately than the same numbers buried in prose.",
    "Present figures in HTML tables with clear headers."),
"geo_list_variety": ("Lists", MEDIUM, LO,
    "Lists are among the most reliably extracted structures on any page.",
    "Convert suitable content into bulleted and numbered lists."),
"geo_format_variety": ("Formatting variety", MEDIUM, LO,
    "A page of unbroken prose gives AI no structural cues about what matters. Bold, lists, tables and quotes all act as emphasis signals.",
    "Mix bold text, lists, tables and blockquotes through the content."),
"geo_multi_perspective": ("Balanced perspective", MEDIUM, ME,
    "Content acknowledging trade-offs reads as objective and is preferred by AI over one-sided marketing copy.",
    "Include when your solution is not the right fit, and what the alternatives are."),
"geo_actionable": ("Actionable advice", HIGH, ME,
    "Practical, specific advice is what assistants surface when users ask how to do something — and it builds trust with the reader.",
    "Give concrete, specific recommendations rather than generalities."),
"geo_conclusion": ("Conclusion and recommendation", MEDIUM, LO,
    "A clear closing recommendation gives AI a definitive answer to lift rather than leaving it to synthesise one.",
    "End key pages with a clear recommendation or next step."),
"geo_img_alt_quality": ("ALT text quality", MEDIUM, LO,
    "One-word ALT text technically passes but conveys nothing to a screen reader or an AI system.",
    "Write ALT text that describes what the image actually shows."),
"geo_image_captions": ("Image captions", LOW, LO,
    "Captions sit in the content itself and are read as descriptive text, unlike ALT attributes.",
    "Wrap images in <figure> with a <figcaption>."),

# ── GEO :: semantic ──────────────────────────────────────────────────────────
"geo_entity_markup": ("Entity markup", MEDIUM, ME,
    "Schema entity types let AI classify precisely what your content is about rather than guessing from words.",
    "Add specific schema types for your services, products and organisation."),
"geo_semantic_depth": ("Semantic HTML depth", MEDIUM, ME,
    "Rich semantic markup gives machines a structural map of the page instead of an undifferentiated block of divs.",
    "Use article, section, aside, figure, nav, header, footer, time and address elements."),
"geo_time_element": ("Time elements", LOW, LO,
    "Machine-readable dates remove ambiguity about when content and events actually happened.",
    'Wrap dates in <time datetime="2026-08-03">.'),
"geo_numerical_density": ("Numerical detail", MEDIUM, LO,
    "Specific numbers with units are far more citable than vague claims like 'fast' or 'many clients'.",
    "Replace vague claims with numbers: years, counts, percentages, turnaround times."),
"geo_keyword_prominence": ("Keyword prominence", MEDIUM, LO,
    "Key terms appearing early confirm to AI that the page delivers on the promise in its title.",
    "Place primary terms within the first 200 words."),
"geo_cross_references": ("Contextual cross-links", MEDIUM, LO,
    "In-content links between related pages demonstrate topical depth rather than isolated pages.",
    "Link naturally from body copy to related pages."),
"geo_categorization": ("Content categorisation", LOW, LO,
    "Clear categories help AI place your content within a subject area.",
    "Use categories, tags or schema about/mentions properties."),
"geo_subtopic_depth": ("Subtopic depth", MEDIUM, ME,
    "H3 subsections under main headings show a topic has been covered properly rather than skimmed.",
    "Add H3 subsections under each major heading."),
"geo_anchor_quality": ("Anchor text quality", MEDIUM, LO,
    "Descriptive link text tells AI what the linked page is about, strengthening both pages.",
    "Use descriptive anchor text rather than 'here' or a bare URL."),
"geo_video_schema": ("Video schema", LOW, ME,
    "VideoObject markup makes video content discoverable and citable; only relevant if you publish video.",
    "Add VideoObject schema where video is embedded."),

# ── GEO :: technical ─────────────────────────────────────────────────────────
"geo_mobile": ("Mobile friendliness", CRITICAL, ME,
    "Google indexes the mobile version of your site first. If the mobile experience is broken, that is the version being judged and ranked.",
    "Ensure a proper responsive layout with the viewport tag set."),
"geo_https": ("HTTPS for AI trust", CRITICAL, LO,
    "Insecure sites are distrusted by both browsers and AI systems, and are less likely to be recommended.",
    "Serve everything over HTTPS."),
"geo_page_size": ("Page weight", MEDIUM, ME,
    "Heavy pages load slowly on mobile data and can be truncated or abandoned by crawlers.",
    "Compress images, split bundles and keep pages lean."),
"geo_og_complete": ("Complete Open Graph", MEDIUM, LO,
    "Complete social metadata gives AI a clean, structured summary of the page as a bonus.",
    "Set og:title, og:description and og:image on every page."),
"geo_canonical": ("Canonical for AI citation", HIGH, LO,
    "Without a canonical, an AI may cite a duplicate or parameterised URL, splitting your credit.",
    "Set a self-referencing canonical on every page."),
"geo_robots_ai": ("AI indexing permissions", CRITICAL, LO,
    "noindex or nosnippet directives remove the page from AI answers completely.",
    "Remove noindex and nosnippet from pages you want found."),
"geo_schema_richness": ("Schema richness", MEDIUM, ME,
    "More complete structured data gives AI more confirmed facts to work with when describing you.",
    "Layer Organization, Service, Product and Review schema as applicable."),
"geo_lang_consistency": ("Language signals", LOW, LO,
    "Consistent language and locale declarations prevent the page being served to the wrong audience.",
    "Set the html lang attribute and og:locale to match."),
"geo_aria_landmarks": ("Landmark structure", MEDIUM, LO,
    "Landmarks help machines distinguish the main content from navigation, improving both accessibility and extraction.",
    "Use semantic landmark elements throughout the layout."),
"geo_snippet_control": ("Snippet permissions", HIGH, LO,
    "Restrictive snippet directives prevent AI from quoting you at all, which is usually the opposite of what a business wants.",
    "Allow snippets unless there is a specific commercial reason not to."),

# ── GEO :: trust ─────────────────────────────────────────────────────────────
"geo_no_cloaking": ("Hidden text / cloaking", CRITICAL, LO,
    "Text hidden from visitors but visible to crawlers is a spam pattern that can trigger manual penalties. It is often accidental, left behind by menus, tabs or screen-reader helpers, but the risk is the same.",
    "Audit hidden elements and remove any text not intended for crawlers."),
}
