"""
Platform and architecture constraints.

Some findings simply cannot be fixed on the platform the site is built on. A
closed builder like Wix will not let anyone set a security header no matter how
much they pay, and telling a client to "add a Content-Security-Policy" on Wix is
advice they can never act on.

This module says so plainly: per platform, which checks are hard-blocked, which
are constrained, and what the realistic alternative is.

    BLOCKED  — not fixable on this stack. The only real fix is replatforming.
    LIMITED  — fixable, but constrained by the platform or costly to do properly.

Written conservatively: platforms change, so the wording says "typically" and the
report frames these as things to confirm rather than absolutes.
"""

BLOCKED, LIMITED = "blocked", "limited"

# Header-level checks a closed hosting platform will not expose.
_HEADERS = ["csp", "hsts", "x_content_type", "referrer_policy",
            "permissions_policy", "cache_control", "compression"]

# Checks driven by a builder's own page renderer, not by the site owner.
_RENDERER = ["inline_js", "inline_css", "dom_size", "render_blocking",
             "script_defer", "text_html_ratio", "resource_hints", "font_preload",
             "html_doctype", "duplicate_ids", "deprecated_html"]

# Arbitrary files at the domain root.
_ROOT_FILES = ["aeo_llms_txt", "geo_ai_discovery", "indexnow"]


def _spread(ids, status, reason):
    return {i: (status, reason) for i in ids}


PLATFORMS = {

"wix": {
    "name": "Wix",
    "kind": "Closed hosted website builder",
    "control": "Low — Wix owns the server, the HTML output and the file system.",
    "good": "Genuinely fast to launch, hosting and TLS handled, and the built-in SEO "
            "panel covers titles, descriptions, canonical tags and structured data.",
    "wall": "Wix serves every site from its own infrastructure and generates the HTML "
            "itself. You control the content and some meta tags; you do not control "
            "response headers, the markup the renderer produces, or what sits at the "
            "domain root. Several findings in this report sit on the far side of that "
            "line — no developer, budget or plugin changes that.",
    "verdict": "If the blocked items matter to the business — security headers for a "
               "site taking personal information, or page weight on mobile data — the "
               "honest answer is a rebuild on an open stack, not more work on Wix.",
    "constraints": {
        **_spread(_HEADERS, BLOCKED,
                  "Wix does not expose response headers. This cannot be set on the platform."),
        **_spread(_RENDERER, LIMITED,
                  "This markup is produced by Wix's own renderer. You can reduce apps and "
                  "media, but the underlying structure is not editable."),
        **_spread(_ROOT_FILES, BLOCKED,
                  "Wix does not allow arbitrary files at the domain root."),
        "robots_txt": (LIMITED, "Editable only through Wix's SEO tools, not as a free-form file."),
        "sitemap_xml": (LIMITED, "Auto-generated by Wix and not directly editable."),
        "robots_txt_sitemap": (LIMITED, "Managed by Wix; not manually editable."),
        "rss_feed": (LIMITED, "Only available where Wix Blog is in use."),
        "img_modern_format": (LIMITED, "Wix converts and serves images through its own CDN."),
        "img_responsive": (LIMITED, "Handled by the Wix image pipeline, not by hand."),
        "aria_landmarks": (LIMITED, "Depends on the Wix template; limited manual control."),
        "aeo_semantic_html": (LIMITED, "Wix outputs generic containers rather than semantic HTML5."),
        "geo_semantic_depth": (LIMITED, "Constrained by Wix's generated markup."),
        "hreflang": (LIMITED, "Only via the Wix Multilingual app."),
        "iframe_sandbox": (LIMITED, "Third-party Wix apps control their own embeds."),
    },
},

"squarespace": {
    "name": "Squarespace",
    "kind": "Closed hosted website builder",
    "control": "Low to moderate — head-level code injection is allowed; the server is not.",
    "good": "Strong templates, reliable hosting, and code injection means schema, meta "
            "tags and analytics can all be added properly.",
    "wall": "Squarespace runs the infrastructure and generates the page markup. Code "
            "injection lets you add things to <head>, but it cannot change response "
            "headers, restructure the rendered HTML, or place files at the domain root. "
            "robots.txt is managed by Squarespace and not editable.",
    "verdict": "Fine for a brochure site where content is the priority. If security "
               "headers, crawl control or page-weight tuning are genuinely needed, those "
               "requirements point to an open stack.",
    "constraints": {
        **_spread(_HEADERS, BLOCKED,
                  "Squarespace does not expose response headers to site owners."),
        **_spread(_RENDERER, LIMITED,
                  "Generated by the Squarespace template engine; only partly influenced by "
                  "template and block choices."),
        **_spread(_ROOT_FILES, BLOCKED,
                  "Squarespace does not serve arbitrary files from the domain root."),
        "robots_txt": (BLOCKED, "Squarespace manages robots.txt and does not allow edits."),
        "sitemap_xml": (LIMITED, "Auto-generated; contents not directly editable."),
        "robots_txt_sitemap": (BLOCKED, "Controlled by Squarespace."),
        "ai_crawlers_blocked": (LIMITED, "Governed by Squarespace's platform-level crawler settings."),
        "aeo_ai_crawlers": (LIMITED, "Governed by Squarespace's platform-level crawler settings."),
        "geo_bot_access": (LIMITED, "Governed by Squarespace's platform-level crawler settings."),
        "img_modern_format": (LIMITED, "Squarespace's image CDN decides the delivered format."),
        "img_responsive": (LIMITED, "Handled by the platform image pipeline."),
        "aeo_semantic_html": (LIMITED, "Determined by the chosen template."),
        "geo_semantic_depth": (LIMITED, "Determined by the chosen template."),
        "aria_landmarks": (LIMITED, "Template-controlled."),
    },
},

"shopify": {
    "name": "Shopify",
    "kind": "Hosted commerce platform with theme-level access",
    "control": "Moderate — full theme and template control, no server control.",
    "good": "Theme files, structured data, meta tags, internal linking and content are "
            "all fully editable, and robots.txt can be customised through "
            "robots.txt.liquid. Most on-page findings are genuinely fixable.",
    "wall": "Shopify controls the servers, so response headers are off limits, and the "
            "URL structure is fixed: products live under /products/ and collections "
            "under /collections/ whether that suits your SEO or not. Installed apps "
            "inject their own scripts into every page, which is the usual cause of speed "
            "findings — the fix there is removing apps, not optimising code.",
    "verdict": "Almost everything content and structure related is fixable. Header-level "
               "security items are not, and on standard plans neither is the checkout.",
    "constraints": {
        **_spread(_HEADERS, BLOCKED,
                  "Shopify controls response headers. Not configurable on any standard plan."),
        **_spread(_ROOT_FILES, LIMITED,
                  "Shopify does not serve arbitrary root files; only limited routes are available."),
        "url_length": (LIMITED, "Shopify enforces /products/ and /collections/ URL prefixes."),
        "url_hyphens": (LIMITED, "Handle format is largely enforced by Shopify."),
        "third_party_scripts": (LIMITED,
            "Injected by installed apps. Reducing this means removing apps, not editing code."),
        "inline_js": (LIMITED, "Much of this comes from Shopify's core scripts and installed apps."),
        "render_blocking": (LIMITED, "App scripts inject themselves ahead of your theme code."),
        "dom_size": (LIMITED, "Driven by theme architecture and app widgets."),
        "canonical": (LIMITED, "Shopify sets canonicals automatically; overrides need theme edits."),
        "iframe_sandbox": (LIMITED, "Third-party app embeds control their own iframes."),
        "hreflang": (LIMITED, "Requires Shopify Markets or a translation app."),
    },
},

"wordpress": {
    "name": "WordPress",
    "kind": "Self-hosted open source CMS",
    "control": "High — full access to code, server, headers and files.",
    "good": "Nothing in this report is structurally impossible on WordPress. Headers, "
            "markup, schema, robots.txt, root files and caching are all reachable, "
            "whether through a plugin or at server level.",
    "wall": "The constraints here are practical rather than architectural. Page builders "
            "such as Elementor and Divi generate deeply nested markup that inflates page "
            "weight and dilutes the text-to-code ratio, and that is difficult to unwind "
            "without rebuilding the templates. Shared hosting may also not expose header "
            "configuration, and every additional plugin adds both weight and attack surface.",
    "verdict": "Every item in this report is fixable. Cost is driven by how much of the "
               "site sits inside a page builder and how much control the host allows.",
    "constraints": {
        "text_html_ratio": (LIMITED,
            "Where a page builder is in use, the nested markup causing this is generated by "
            "the builder and only removable by rebuilding the template."),
        "dom_size": (LIMITED, "Page builder output. Reducing it usually means rebuilding the page."),
        "inline_css": (LIMITED, "Page builders and themes inject their own inline styles."),
        "inline_js": (LIMITED, "Plugins inject scripts inline; reducing this means auditing plugins."),
        "third_party_scripts": (LIMITED, "Driven by installed plugins rather than by theme code."),
        **_spread(["csp", "hsts", "permissions_policy", "referrer_policy",
                   "x_content_type", "cache_control"], LIMITED,
                  "Straightforward on a VPS or with a CDN in front. Some shared hosts do not "
                  "expose header configuration."),
    },
},

"nextjs": {
    "name": "Next.js",
    "kind": "Custom React application framework",
    "control": "Full — this is bespoke code with complete control.",
    "good": "Everything in this report is reachable: headers in configuration, rendering "
            "mode per route, structured data, caching and root files. Nothing is blocked "
            "by the platform.",
    "wall": "The one structural caveat is how React works. The framework ships a "
            "serialised copy of the page's data alongside the visible HTML for hydration, "
            "so a Next.js page will always look code-heavy to a text-to-HTML ratio check "
            "even when it is perfectly well built. That specific finding is close to "
            "unavoidable — the meaningful response is more real content, not less code. "
            "The genuine risk is the opposite one: any route rendered only in the browser "
            "is invisible to AI crawlers that do not run JavaScript.",
    "verdict": "No hard platform blockers. Confirm every important page is server-rendered "
               "or statically generated rather than client-side only.",
    "constraints": {
        "text_html_ratio": (LIMITED,
            "React hydration data inflates the HTML by design. Largely structural — improve "
            "by adding real content rather than by chasing the ratio."),
        "inline_js": (LIMITED,
            "The framework inlines its hydration payload. Not removable without changing "
            "rendering strategy."),
        "dom_size": (LIMITED, "Component-driven markup is inherently more nested."),
        "aeo_html_content": (LIMITED,
            "Depends entirely on rendering mode. Client-rendered routes are invisible to "
            "crawlers that do not execute JavaScript — check this per route."),
        "render_blocking": (LIMITED, "Framework bundles load early by design."),
    },
},

"gatsby": {
    "name": "Gatsby",
    "kind": "Static site generator (React)",
    "control": "Full — static output with complete control over hosting and headers.",
    "good": "Pages are pre-built as static HTML, which is ideal for crawlers and AI. "
            "Headers and root files are set at the host or CDN, so nothing is blocked.",
    "wall": "As with any React framework, hydration data is embedded in the page, so the "
            "text-to-code ratio reads worse than it really is. Content changes also "
            "require a rebuild and redeploy, which is a workflow constraint rather than a "
            "technical one.",
    "verdict": "No platform blockers. Structural findings relate to React output, not to "
               "anything that needs fixing.",
    "constraints": {
        "text_html_ratio": (LIMITED, "React hydration payload inflates HTML size by design."),
        "inline_js": (LIMITED, "Framework hydration script, not optional."),
        "dom_size": (LIMITED, "Component-driven markup is more nested by nature."),
    },
},

"nuxt": {
    "name": "Nuxt",
    "kind": "Custom Vue application framework",
    "control": "Full — complete control over rendering, headers and files.",
    "good": "Rendering mode is configurable per route, and headers, schema and root files "
            "are all reachable. Nothing here is blocked by the framework.",
    "wall": "Vue hydration state is serialised into the page, so text-to-code ratio "
            "readings are pessimistic. As with any JavaScript framework, any route left "
            "client-rendered will not be seen by crawlers that do not run JavaScript.",
    "verdict": "No hard blockers. Verify that important routes are server-rendered or "
               "pre-generated.",
    "constraints": {
        "text_html_ratio": (LIMITED, "Vue hydration state inflates HTML by design."),
        "inline_js": (LIMITED, "Framework hydration payload."),
        "aeo_html_content": (LIMITED,
            "Client-rendered routes are invisible to non-JavaScript crawlers. Verify per route."),
        "dom_size": (LIMITED, "Component-driven markup is inherently more nested."),
    },
},

"drupal": {
    "name": "Drupal",
    "kind": "Self-hosted open source CMS",
    "control": "High — full access to templates, server and configuration.",
    "good": "Drupal exposes markup, headers, routing and files completely. Every finding "
            "in this report is technically addressable.",
    "wall": "The constraint is effort, not capability. Drupal changes usually mean theme "
            "and module work by a Drupal developer rather than a settings toggle, so the "
            "same fix costs more here than on a lighter platform.",
    "verdict": "Everything is fixable. Budget for developer time rather than configuration.",
    "constraints": {
        "dom_size": (LIMITED, "Drupal's render pipeline produces heavily nested markup."),
        "text_html_ratio": (LIMITED, "Theme wrappers add substantial markup around content."),
    },
},

"magento": {
    "name": "Magento / Adobe Commerce",
    "kind": "Self-hosted enterprise commerce platform",
    "control": "High — full server and template access.",
    "good": "Full control over headers, markup, schema and files. No architectural blocks.",
    "wall": "Magento is heavy by design. Large DOMs, substantial JavaScript and slow "
            "first loads are characteristic of the platform, and improving them means "
            "serious infrastructure work — full page caching, Varnish, image CDN — rather "
            "than front-end tweaks.",
    "verdict": "Nothing is blocked, but performance findings are platform-level work, not "
               "quick fixes.",
    "constraints": {
        "dom_size": (LIMITED, "Characteristic of Magento's layout system."),
        "inline_js": (LIMITED, "Magento's RequireJS architecture inlines substantial script."),
        "render_blocking": (LIMITED, "Core bundles load early by design."),
        "text_html_ratio": (LIMITED, "Layout XML produces markup-heavy pages."),
    },
},

"opencart": {
    "name": "OpenCart",
    "kind": "Self-hosted open source commerce platform",
    "control": "High — full access to templates and server.",
    "good": "Templates, headers and files are all editable. No platform-level blocks.",
    "wall": "OpenCart's default themes are dated, and much of the ecosystem relies on "
            "extensions that overwrite core files, which makes clean structural fixes "
            "harder to apply and to keep through upgrades.",
    "verdict": "Fixable throughout, though extension conflicts can make the work fiddlier "
               "than the same job elsewhere.",
    "constraints": {
        "dom_size": (LIMITED, "Default themes use table-heavy legacy markup."),
        "aeo_semantic_html": (LIMITED, "Older theme markup predates semantic HTML5 conventions."),
    },
},

"_generic": {
    "name": "Custom or undetected platform",
    "kind": "Not identified by the scan",
    "control": "Unknown — confirm with whoever maintains the site.",
    "good": "No platform signature was detected, which usually means a custom build or a "
            "less common CMS. Custom builds normally allow every fix in this report.",
    "wall": "Without knowing the stack we cannot say for certain which items are blocked. "
            "The pattern is consistent though: closed hosted builders (Wix, Squarespace, "
            "and similar) never expose response headers or domain-root files, so those "
            "findings are unfixable there. Open stacks — WordPress, custom applications, "
            "anything you host yourself — can address everything here given budget.",
    "verdict": "Confirm the hosting arrangement before committing to the security and "
               "header items in this report.",
    "constraints": {},
},
}

# Findings that are usually a symptom of the platform rather than of the site.
ARCHITECTURAL = {
    "text_html_ratio", "inline_js", "inline_css", "dom_size", "render_blocking",
    "script_defer", "aeo_html_content", "aeo_semantic_html", "geo_semantic_depth",
}


def profile(detected_cms):
    """Return the platform profile for a detected CMS key."""
    key = (detected_cms or "").strip().lower()
    return PLATFORMS.get(key, PLATFORMS["_generic"]), key in PLATFORMS


def constraint(prof, check_id):
    """(status, reason) for a check on this platform, or None."""
    return prof.get("constraints", {}).get(check_id)
