#!/usr/bin/env python3
"""
Boldpiq Website Audit — web front end.

A small HTTP service that wraps seo_report.py so staff can generate a client
visibility report from a browser instead of a terminal. Standard library only,
matching the rest of the tool.

Design notes worth keeping:

- ONE WORKER, ON PURPOSE. Jobs run strictly one at a time. seoscore.tools' terms
  forbid excessive scanning, and a headless Chrome run is the heaviest thing on
  the box. Serialising also means a queue of three is 2 minutes, not three
  simultaneous Chrome instances fighting for RAM.
- NO AUTHENTICATION HERE. This sits behind Cloudflare Access, the same as n8n.
  Do not expose the port directly to the internet — there is nothing stopping
  anyone from queueing scans.
- The report is generated by shelling out to the CLI rather than importing it,
  so a crash in one scan can never take the server down, and the CLI stays the
  single source of truth for how a report is built.
"""

import datetime as dt
import json
import mimetypes
import os
import queue
import re
import shutil
import subprocess
import sys
import threading
import time
import urllib.parse
import uuid
from http.server import BaseHTTPRequestHandler, ThreadingHTTPServer

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
sys.path.insert(0, ROOT)

import runtime  # noqa: E402  (needs ROOT on the path first)

sys.path.insert(0, HERE)
import profiles  # noqa: E402

REPORTS = os.environ.get("BOLDPIQ_REPORTS") or os.path.join(ROOT, "reports")
PORT = int(os.environ.get("PORT", "8090"))
HOST = os.environ.get("HOST", "0.0.0.0")
# Courtesy gap between consecutive scans, on top of running them one at a time.
# rank-report is a sibling directory, not a copy. It imports runtime.py and the
# Geist font from seo-report so both reports look like the same document family.
# Local dev: ../rank-report (sibling checkout). In the image it is staged to
# /app/rank-report by the Dockerfile. Whichever exists wins.
_RANK_CANDIDATES = [os.path.join(ROOT, "rank-report"),
                    os.path.join(ROOT, "..", "rank-report")]
RANK_ROOT = os.environ.get("BOLDPIQ_RANK_ROOT") or next(
    (p for p in _RANK_CANDIDATES if os.path.isdir(p)), _RANK_CANDIDATES[-1])

# Search Console exports uploaded from the browser. This is the client's own
# Google data — held only as long as the job that consumes it, then deleted.
# Remembered per-client inputs, so a monthly report is one click rather than
# fifteen fields. Kept beside the reports, which is already the data directory
# and already backed up.
PROFILES = os.environ.get("BOLDPIQ_PROFILES") or REPORTS

UPLOADS = os.environ.get("BOLDPIQ_UPLOADS") or os.path.join(REPORTS, "_uploads")
MAX_UPLOAD_BYTES = int(os.environ.get("BOLDPIQ_MAX_UPLOAD", str(25 * 1024 * 1024)))
UPLOAD_EXTS = (".csv", ".zip", ".xlsx")

JOB_GAP_SECONDS = int(os.environ.get("BOLDPIQ_JOB_GAP", "6"))
JOB_TIMEOUT = int(os.environ.get("BOLDPIQ_JOB_TIMEOUT", "600"))
# Whole-site audits measure every page in Chrome one at a time (~1 min a page in
# the container), so they need far longer than a single-page run. The per-page
# allowance is generous on purpose: a timeout throws the whole report away.
SITE_MAX_PAGES = int(os.environ.get("BOLDPIQ_SITE_MAX_PAGES", "100"))
SITE_SECONDS_PER_PAGE = int(os.environ.get("BOLDPIQ_SITE_SECONDS_PER_PAGE", "150"))
# The ranking report now walks every page (sitemaps + the site's own links)
# before anything else; on a few-hundred-page site that alone is minutes.
RANK_TIMEOUT = int(os.environ.get("BOLDPIQ_RANK_TIMEOUT", "1800"))
SITE_PROGRESS = re.compile(r"\[(\d+)/(\d+)\]\s+measuring in chrome\s+(\S+)")
SCAN_PROGRESS = re.compile(r"scanned (\d+)/(\d+)")
MAX_JOBS_KEPT = 200

VALID_HOST = re.compile(r"^[a-zA-Z0-9]([a-zA-Z0-9\-._]{0,251}[a-zA-Z0-9])?$")

_jobs = {}                    # id -> job dict
_jobs_lock = threading.Lock()
_queue = queue.Queue()


# ── job model ────────────────────────────────────────────────────────────────

# The CLI's own progress lines, mapped to something a non-technical person can
# read. If the CLI's wording changes, only this table needs updating.
PROGRESS = [
    ("scanning",            "Scanning the site's structure…",              15),
    ("measuring in chrome", "Measuring real load speed in Chrome…",        40),
    ("rendering pdf",       "Building the PDF report…",                    85),
    # rank-report's own progress lines
    ("finding every page",  "Reading the sitemap and finding every page…",  8),
    ("crawl gate",          "Checking every page is its own document…",    20),
    ("site structure",      "Checking links, sitemap and duplicates across the site…", 30),
    ("competitors",         "Measuring the competition…",                  50),
    ("proximity",           "Measuring distance to each target area…",     70),
]


def _new_job(url, client, keyphrase, form_factor, lighthouse,
             kind="audit", opts=None):
    job = {
        "id": uuid.uuid4().hex[:12],
        "kind": kind,               # "audit" (visibility report) | "rank" (ranking report)
        "opts": opts or {},         # rank-report only: suburb, queries, competitors, …
        "url": url,
        "client": client,
        "keyphrase": keyphrase,
        "form_factor": form_factor,
        "lighthouse": lighthouse,
        "state": "queued",          # queued | running | done | error
        "message": "Waiting in the queue…",
        "percent": 0,
        "created": time.time(),
        "pdf": None,
        "summary": None,
        "error": None,
        "checks": [],               # sources that did not return data, live
        "checks_summary": None,
    }
    with _jobs_lock:
        _jobs[job["id"]] = job
        if len(_jobs) > MAX_JOBS_KEPT:
            for old in sorted(_jobs.values(), key=lambda j: j["created"])[:20]:
                _jobs.pop(old["id"], None)
    return job


def _set(job, **fields):
    with _jobs_lock:
        job.update(fields)


def _queue_positions():
    """Tell anyone still waiting how many jobs are ahead of them."""
    with _jobs_lock:
        waiting = sorted((j for j in _jobs.values() if j["state"] == "queued"),
                         key=lambda j: j["created"])
    for i, job in enumerate(waiting):
        ahead = i
        _set(job, message="Waiting in the queue…" if not ahead
             else f"Waiting in the queue — {ahead} report{'s' if ahead > 1 else ''} ahead…")


# ── worker ───────────────────────────────────────────────────────────────────

def _run_job(job):
    _set(job, state="running", message="Starting…", percent=5)

    if job.get("kind") == "rank":
        # rank-report lives in a sibling directory and shares runtime.py and the
        # font from here. Same queue, same gap, same timeout — only the command
        # differs, which is the whole reason it is one service and not two.
        o = job.get("opts") or {}
        cmd = [sys.executable, "-u", os.path.join(RANK_ROOT, "rank_report.py"),
               job["url"]]
        if job["client"]:
            cmd += ["--client", job["client"]]
        for flag, key in (("--suburb", "suburb"), ("--queries", "queries"),
                          ("--competitors", "competitors"), ("--areas", "areas"),
                          ("--pin", "pin"), ("--gbp-url", "gbp_url"),
                          ("--money-page", "money_page"), ("--compare", "compare"),
                          ("--gsc", "gsc"), ("--reviews", "reviews"),
                          ("--competitor-reviews", "competitor_reviews"),
                          ("--location", "location"), ("--country", "country")):
            if o.get(key):
                # --flag=value, never --flag value. A map pin in the southern
                # hemisphere starts with a minus sign, and argparse reads a bare
                # "-26.13,27.96" as an unknown option rather than a value. The
                # heuristic that saves plain negative numbers does not apply once
                # there is a comma in it, and it differs between Python versions —
                # which is why this passed locally and failed in the container.
                cmd += [f"{flag}={o[key]}"]
    else:
        cmd = [sys.executable, "-u", os.path.join(ROOT, "seo_report.py"),
               job["url"], "--out", REPORTS, "--no-desktop"]
        if job["client"]:
            cmd += ["--client", job["client"]]
        if job["keyphrase"]:
            cmd += ["--keyphrase", job["keyphrase"]]
        if job["form_factor"] == "desktop":
            cmd += ["--desktop"]
        if (job.get("opts") or {}).get("site"):
            cmd += ["--site", f"--max-pages={job['opts']['max_pages']}"]
        # Lighthouse is mandatory: every report must be a real measurement of the
        # live page, never a structural-scan-only shortcut. The flag is ignored.

    site_job = job.get("kind") != "rank" and (job.get("opts") or {}).get("site")
    timeout = (900 + SITE_SECONDS_PER_PAGE * job["opts"]["max_pages"]) if site_job \
        else RANK_TIMEOUT if job.get("kind") == "rank" else JOB_TIMEOUT
    lines = []
    try:
        proc = subprocess.Popen(cmd, cwd=ROOT, stdout=subprocess.PIPE,
                                stderr=subprocess.STDOUT, text=True, bufsize=1)
    except OSError as err:
        _set(job, state="error", error=f"Could not start the report: {err}")
        return

    deadline = time.time() + timeout
    for line in proc.stdout:
        line = line.rstrip()
        lines.append(line)
        low = line.lower()
        stripped = line.strip()
        if site_job:
            # Page-by-page progress. Chrome is the slow lane, so it drives the bar.
            m = SITE_PROGRESS.search(stripped)
            if m:
                i, n = int(m.group(1)), int(m.group(2))
                _set(job, message=f"Measuring page {i} of {n} in Chrome — {m.group(3)}",
                     percent=12 + round(78 * (i - 1) / max(n, 1)))
            elif SCAN_PROGRESS.search(stripped) and (job.get("percent") or 0) < 12:
                _set(job, message="Scanning every page's structure…", percent=10)
            elif "discovering pages" in low:
                _set(job, message="Reading the sitemap and finding every page…", percent=4)
            elif stripped.startswith("found ") and "live pages" in stripped:
                _set(job, message=stripped[0].upper() + stripped[1:], percent=8)
            elif "checking site structure" in low:
                _set(job, message="Checking links, sitemap and duplicates across the site…",
                     percent=10)
            elif "waiting for the structural scans" in low:
                _set(job, message="Finishing the last structural scans…", percent=90)
            elif "rendering pdf" in low:
                _set(job, message="Building the PDF report…", percent=92)
        else:
            for needle, message, percent in PROGRESS:
                if needle in low:
                    _set(job, message=message, percent=percent)
        if stripped.startswith("CHECK "):
            # One line per source that did not return data. Surfaced live in the
            # panel so a broken key is seen while the operator is still at the
            # screen, rather than discovered by a client reading a gap.
            bits = stripped[len("CHECK "):].split("\t")
            if len(bits) >= 2:
                checks = list(job.get("checks") or [])
                checks.append({"status": bits[0].strip(),
                               "label": bits[1].strip(),
                               "remedy": bits[2].strip() if len(bits) > 2 else ""})
                _set(job, checks=checks)
        elif stripped.startswith("CHECKS:"):
            _set(job, checks_summary=stripped[len("CHECKS:"):].strip())
        elif stripped.endswith("measured in Chrome)") and "pages audited" in stripped:
            _set(job, summary=stripped)
        elif stripped.startswith("overall "):
            prev = job.get("summary") or ""
            _set(job, summary=(prev + "\n" + stripped).strip(),
                 message="Finishing up…", percent=95)
        elif stripped.startswith("lighthouse "):
            # Second summary line. Append rather than replace — dropping it was why
            # reports looked like they had no Chrome measurements.
            prev = job.get("summary") or ""
            _set(job, summary=(prev + "\n" + stripped).strip())
        if time.time() > deadline:
            proc.kill()
            _set(job, state="error",
                 error=f"The scan took longer than {timeout // 60} minutes and was "
                       "stopped. The site may be very slow, or blocking automated "
                       "requests.")
            return

    proc.wait()

    # The export is the client's own Google data. It exists to be read once by
    # this job; holding it past that is retention we have no reason for.
    consumed = (job.get("opts") or {}).get("gsc")
    if consumed and os.path.abspath(os.path.dirname(consumed)) == os.path.abspath(UPLOADS):
        try:
            os.remove(consumed)
        except OSError:
            pass

    pdf = next((ln.strip() for ln in reversed(lines)
                if ln.strip().lower().endswith(".pdf")), None)

    if proc.returncode != 0 or not pdf or not os.path.exists(pdf):
        detail = "\n".join(lines[-6:]).strip() or "No output from the report tool."
        _set(job, state="error", error=detail)
        return

    if job.get("kind") == "rank":
        # Saved only on success: a run that failed halfway may have been given
        # nonsense, and remembering it would hand the same nonsense back next month.
        try:
            profiles.save(PROFILES, job["url"],
                          {**(job.get("opts") or {}), "client": job.get("client")})
        except Exception as err:                       # never fail a good report
            print(f"profiles: could not save: {err}", flush=True)

    _set(job, state="done", percent=100, pdf=os.path.basename(pdf),
         message="Report ready.")


_URL_CACHE = {}


# ── retention ────────────────────────────────────────────────────────────────
# Audits are run against prospects' sites, so the PDFs and their scan JSON are
# third-party data we hold without a contract. POPIA says don't keep it longer
# than the purpose needs. 12 months is the purpose: long enough that a re-scan
# can still be compared against the original, short enough to be defensible.

RETENTION_DAYS = int(os.environ.get("BOLDPIQ_RETENTION_DAYS", "365"))


def _purge_stale_uploads(max_age_hours=24):
    """Delete uploads no job ever consumed.

    A job deletes its own export when it finishes. This catches the ones nobody
    ever submitted — a file picked in the form and then abandoned. Client data
    with no purpose left has no business sitting on disk.
    """
    if not os.path.isdir(UPLOADS):
        return 0
    cutoff = time.time() - max_age_hours * 3600
    removed = 0
    for name in os.listdir(UPLOADS):
        path = os.path.join(UPLOADS, name)
        try:
            if os.stat(path).st_mtime >= cutoff:
                continue
            os.remove(path)
            removed += 1
        except OSError:
            pass
    return removed


def _purge_old_reports():
    """Delete reports past the retention window. Returns the number removed."""
    if RETENTION_DAYS <= 0 or not os.path.isdir(REPORTS):
        return 0
    cutoff = time.time() - RETENTION_DAYS * 86400
    removed = 0
    for name in os.listdir(REPORTS):
        if not name.lower().endswith((".pdf", ".json")):
            continue
        path = os.path.join(REPORTS, name)
        try:
            if os.stat(path).st_mtime >= cutoff:
                continue
            os.remove(path)
            removed += 1
        except OSError:
            continue
    if removed:
        _URL_CACHE.clear()
        print(f"retention: removed {removed} file(s) older than {RETENTION_DAYS} days",
              flush=True)
    return removed


def _retention_loop():
    while True:
        try:
            _purge_old_reports()
            _purge_stale_uploads()
        except Exception as err:                       # never let the sweeper die
            print(f"retention: sweep failed: {err}", flush=True)
        time.sleep(24 * 3600)


def _worker():
    while True:
        job = _queue.get()
        try:
            _run_job(job)
        except Exception as err:                       # never let the worker die
            _set(job, state="error", error=f"Unexpected failure: {err}")
        finally:
            _queue.task_done()
            _queue_positions()
            time.sleep(JOB_GAP_SECONDS)


# ── report listing ───────────────────────────────────────────────────────────


def _report_url(pdf_name, mtime):
    """The audited URL, read from the report's JSON companion. Cached per file by mtime.

    One entry per report, replaced when the file changes. (This used to clear the
    whole cache on every miss, so every listing re-read every JSON — harmless at
    40 KB, not with multi-megabyte whole-site records.)
    """
    hit = _URL_CACHE.get(pdf_name)
    if hit and hit[0] == mtime:
        return hit[1]
    url = ""
    if pdf_name.lower().endswith(".pdf"):
        side = os.path.join(REPORTS, pdf_name[:-4] + ".json")
        try:
            with open(side, "r", encoding="utf-8") as fh:
                url = (json.load(fh) or {}).get("url") or ""
        except (OSError, ValueError):
            url = ""
    _URL_CACHE[pdf_name] = (mtime, url)
    return url


def _recent_reports(limit=25):
    if not os.path.isdir(REPORTS):
        return []
    out = []
    for name in os.listdir(REPORTS):
        if not name.lower().endswith(".pdf"):
            continue
        path = os.path.join(REPORTS, name)
        try:
            stat = os.stat(path)
        except OSError:
            continue
        base = os.path.join(REPORTS, name[:-4])
        site, _, rest = name.partition("-visibility-report-")
        out.append({"file": name,
                    "site": site,
                    "scope": "site" if rest.startswith("site-") else "page",
                    "url": _report_url(name, stat.st_mtime),
                    "fixes": os.path.isfile(base + "-fixes.json")
                             or os.path.isfile(base + ".json"),
                    "size_kb": round(stat.st_size / 1024),
                    "modified": stat.st_mtime})
    out.sort(key=lambda r: r["modified"], reverse=True)
    return out[:limit]


# ── fix packs ────────────────────────────────────────────────────────────────
# The PDF is for the client; the fix pack is the same findings compressed for
# pasting into an AI. seo_report.py writes one next to every new report. Older
# reports predate that, so we rebuild theirs on the fly from the scan JSON —
# without the Lighthouse sections, which the scan JSON does not carry.

def _reconcile(pack, base):
    """Make the pack's headline scores agree with the scan that produced the report.

    The scan JSON is the record of what was measured, so it wins. This repairs packs
    written before Lighthouse's own "seo" category stopped overwriting the SEO pillar,
    and catches any future drift between the PDF and this page rather than letting the
    two quietly disagree in front of a client.
    """
    try:
        with open(base + ".json", "r", encoding="utf-8") as fh:
            data = json.load(fh)
    except (OSError, ValueError):
        return pack
    scores = pack.get("scores") or {}
    pillars = []
    for key in ("seo", "aeo", "geo"):
        val = (data.get(key) or {}).get("score")
        if not isinstance(val, (int, float)):
            continue
        if scores.get(key) != val:
            if key == "seo" and scores.get("lighthouse-seo") is None:
                scores["lighthouse-seo"] = scores.get(key)   # what had overwritten it
            scores[key] = val
        pillars.append(val)
    if pillars:
        scores["overall"] = round(sum(pillars) / len(pillars))
    pack["scores"] = scores
    if pack.get("preamble"):
        import fixpack
        pack["preamble"] = fixpack._preamble(pack)
        for sec in pack.get("sections", []):
            sec["markdown"] = fixpack._section_markdown(pack, sec)
        pack["markdown"] = fixpack._full_markdown(pack)
    return pack


def _fixpack_for(pdf_name):
    """(pack, error). Reads the companion file, else derives one from the scan JSON."""
    if not pdf_name.lower().endswith(".pdf"):
        return None, "Report not found."
    base = os.path.join(REPORTS, pdf_name[:-4])

    side = base + "-fixes.json"
    if os.path.isfile(side):
        try:
            with open(side, "r", encoding="utf-8") as fh:
                return _reconcile(json.load(fh), base), None
        except (OSError, ValueError):
            pass                       # fall through and rebuild it

    scan_json = base + ".json"
    if not os.path.isfile(scan_json):
        return None, ("No scan data was kept for this report, so the fix list "
                      "cannot be rebuilt. Re-run the audit.")
    try:
        with open(scan_json, "r", encoding="utf-8") as fh:
            data = json.load(fh)
        if data.get("mode") == "site":
            # Every whole-site run writes its own pack; there is no older format
            # to rebuild from. Analysing this file as one page would be nonsense.
            return None, ("The fix list for this whole-site report is missing. "
                          "Re-run the audit.")
        import seo_report                      # local: never break the server on import
        import fixpack
        an = seo_report.analyse(data)
        an["lh"] = None                        # not re-measurable from saved data
        stamp = dt.datetime.fromtimestamp(os.stat(scan_json).st_mtime)
        pack = fixpack.build(data, an, None, stamp)
        pack["derived"] = True
        return pack, None
    except Exception as err:
        return None, f"Could not build the fix list: {err}"


# ── http ─────────────────────────────────────────────────────────────────────

class Handler(BaseHTTPRequestHandler):
    server_version = "BoldpiqAudit/1.0"

    def log_message(self, fmt, *args):               # quieter, still useful
        sys.stderr.write("%s %s\n" % (self.address_string(), fmt % args))

    # -- helpers --
    def _send(self, code, body, ctype="application/json; charset=utf-8",
              extra=None):
        if isinstance(body, (dict, list)):
            body = json.dumps(body).encode()
        elif isinstance(body, str):
            body = body.encode()
        self.send_response(code)
        self.send_header("Content-Type", ctype)
        self.send_header("Content-Length", str(len(body)))
        self.send_header("X-Content-Type-Options", "nosniff")
        self.send_header("Referrer-Policy", "no-referrer")
        # Report names carry only the date, so re-running a site the same day reuses
        # the identical URL with different data behind it. Without this a browser
        # happily serves the earlier run's fix pack next to the new run's scores.
        self.send_header("Cache-Control", "no-store, must-revalidate")
        for k, v in (extra or {}).items():
            self.send_header(k, v)
        self.end_headers()
        if self.command != "HEAD":
            self.wfile.write(body)

    def _public(self, job):
        keep = ("id", "url", "client", "state", "message", "percent", "pdf",
                "summary", "error", "checks", "checks_summary")
        with _jobs_lock:
            out = {k: job.get(k) for k in keep}
            out["scope"] = "site" if (job.get("opts") or {}).get("site") else "page"
            return out

    # -- routes --
    def do_GET(self):
        path = urllib.parse.urlparse(self.path).path

        if path in ("/", "/index.html"):
            return self._file(os.path.join(HERE, "static", "index.html"),
                              "text/html; charset=utf-8")

        if path in ("/rank", "/rank.html"):
            return self._file(os.path.join(HERE, "static", "rank.html"),
                              "text/html; charset=utf-8")

        if path == "/api/health":
            chrome = runtime.chrome_label()
            lh_bin, node = None, None
            try:
                import lighthouse as lh
                lh_bin, node = lh.available()
            except Exception:
                pass
            return self._send(200, {
                "ok": bool(chrome),
                "browser": chrome,
                "lighthouse": bool(lh_bin),
                "queued": _queue.qsize(),
            })

        if path.startswith("/fixes/"):
            return self._file(os.path.join(HERE, "static", "fixes.html"),
                              "text/html; charset=utf-8")

        if path.startswith("/api/fixes/"):
            name = os.path.basename(urllib.parse.unquote(path[len("/api/fixes/"):]))
            known = {r["file"] for r in _recent_reports(limit=10_000)}
            if name not in known:
                return self._send(404, {"error": "Report not found."})
            pack, err = _fixpack_for(name)
            if err:
                return self._send(404, {"error": err})
            return self._send(200, pack)

        if path == "/api/reports":
            return self._send(200, {"reports": _recent_reports()})

        if path == "/api/clients":
            try:
                return self._send(200, {"clients": profiles.listing(PROFILES)})
            except Exception as err:
                return self._send(500, {"error": str(err)})

        if path.startswith("/api/job/"):
            job = _jobs.get(path.rsplit("/", 1)[-1])
            if not job:
                return self._send(404, {"error": "No such job."})
            return self._send(200, self._public(job))

        if path.startswith("/download/"):
            name = urllib.parse.unquote(path[len("/download/"):])
            # Basename only — never let a request walk out of the reports dir.
            name = os.path.basename(name)
            target = os.path.join(REPORTS, name)
            if not name.lower().endswith(".pdf") or not os.path.isfile(target):
                return self._send(404, {"error": "Report not found."})
            return self._file(target, "application/pdf",
                              disposition=f'inline; filename="{name}"')

        return self._send(404, {"error": "Not found."})

    def do_HEAD(self):
        self.do_GET()

    def do_DELETE(self):
        path = urllib.parse.urlparse(self.path).path
        prefix = "/api/reports/"
        if not path.startswith(prefix):
            return self._send(404, {"error": "Not found."})

        name = urllib.parse.unquote(path[len(prefix):])
        # Validate by membership in the real listing, not by sanitising the input:
        # a name that is not already a report we serve is simply not deletable.
        known = {r["file"] for r in _recent_reports(limit=10_000)}
        if name not in known:
            return self._send(404, {"error": "That report no longer exists."})

        removed = []
        stem = name[:-4] if name.lower().endswith(".pdf") else None
        for candidate in (name, stem + ".json" if stem else None,
                          stem + "-fixes.json" if stem else None):
            if not candidate:
                continue
            target = os.path.join(REPORTS, candidate)
            # Belt and braces: the resolved path must still sit inside REPORTS.
            if os.path.realpath(os.path.dirname(target)) != os.path.realpath(REPORTS):
                continue
            try:
                os.remove(target)
                removed.append(candidate)
            except FileNotFoundError:
                pass            # the .json companion may legitimately not exist
            except OSError as e:
                return self._send(500, {"error": f"Could not delete: {e}"})

        return self._send(200, {"deleted": removed})

    def _upload(self):
        """Take one Search Console export and hand back a token for it.

        Raw body plus an X-Filename header rather than multipart: the file is the
        entire request, and stdlib multipart parsing buys nothing here. The name
        is used only for its extension and to show the operator what they picked;
        the stored path is a generated id, so nothing a browser sends becomes a
        filename on disk.
        """
        length = int(self.headers.get("Content-Length") or 0)
        if length <= 0:
            return self._send(400, {"error": "No file received."})
        if length > MAX_UPLOAD_BYTES:
            return self._send(413, {"error": "That file is larger than "
                                             f"{MAX_UPLOAD_BYTES // (1024 * 1024)} MB."})
        given = os.path.basename(self.headers.get("X-Filename") or "export")
        ext = os.path.splitext(given)[1].lower()
        if ext not in UPLOAD_EXTS:
            return self._send(400, {"error": "Search Console exports are .csv, .zip "
                                             "or .xlsx. Use Export → Download CSV or "
                                             "Download Excel."})
        os.makedirs(UPLOADS, exist_ok=True)
        token = uuid.uuid4().hex[:16]
        target = os.path.join(UPLOADS, token + ext)
        remaining, written = length, 0
        try:
            with open(target, "wb") as fh:
                while remaining > 0:
                    chunk = self.rfile.read(min(65536, remaining))
                    if not chunk:
                        break
                    fh.write(chunk)
                    remaining -= len(chunk)
                    written += len(chunk)
        except OSError as err:
            return self._send(500, {"error": f"Could not store the file: {err}"})
        if written == 0:
            os.remove(target)
            return self._send(400, {"error": "The file was empty."})
        return self._send(200, {"token": token, "name": given, "bytes": written})

    def _upload_path(self, token):
        """Resolve a token to a stored file. Token only — never a client path."""
        if not token or not re.fullmatch(r"[0-9a-f]{16}", token):
            return None
        for ext in UPLOAD_EXTS:
            cand = os.path.join(UPLOADS, token + ext)
            if os.path.isfile(cand):
                return cand
        return None

    def do_POST(self):
        path = urllib.parse.urlparse(self.path).path
        if path == "/api/upload":
            return self._upload()
        if path not in ("/api/scan", "/api/rank"):
            return self._send(404, {"error": "Not found."})

        length = int(self.headers.get("Content-Length") or 0)
        if length > 10_000:
            return self._send(413, {"error": "Request too large."})
        try:
            payload = json.loads(self.rfile.read(length) or "{}")
        except ValueError:
            return self._send(400, {"error": "Malformed request."})

        url = (payload.get("url") or "").strip()
        if not url:
            return self._send(400, {"error": "Enter a website address."})
        url = _normalise(url)
        if not url:
            return self._send(400, {"error":
                                    "That doesn't look like a website address. "
                                    "Try something like clientdomain.co.za"})

        if path == "/api/rank":
            opts = {k: (payload.get(k) or "").strip()[:600] for k in
                    ("suburb", "queries", "competitors", "areas",
                     "pin", "gbp_url", "money_page", "compare",
                     "reviews", "competitor_reviews", "location", "country")}
            opts = {k: v for k, v in opts.items() if v}
            gsc_path = self._upload_path((payload.get("gsc_token") or "").strip())
            if gsc_path:
                opts["gsc"] = gsc_path
            elif payload.get("gsc_token"):
                return self._send(400, {"error": "That upload has expired. "
                                                 "Attach the export again."})
            job = _new_job(
                url=url,
                client=(payload.get("client") or "").strip()[:120],
                keyphrase="", form_factor="mobile", lighthouse=False,
                kind="rank", opts=opts,
            )
        else:
            # Whole site is the default: a website is every page, not the one
            # address typed in. "single_page" is the deliberate opt-out.
            site = not payload.get("single_page")
            try:
                max_pages = int(payload.get("max_pages") or SITE_MAX_PAGES)
            except (TypeError, ValueError):
                max_pages = SITE_MAX_PAGES
            max_pages = max(1, min(max_pages, SITE_MAX_PAGES))
            job = _new_job(
                url=url,
                client=(payload.get("client") or "").strip()[:120],
                keyphrase=(payload.get("keyphrase") or "").strip()[:120],
                form_factor="desktop" if payload.get("desktop") else "mobile",
                lighthouse=True,   # always — see _run_job
                opts={"site": True, "max_pages": max_pages} if site else {},
            )
        _queue.put(job)
        _queue_positions()
        return self._send(202, self._public(job))

    def _file(self, path, ctype, disposition=None):
        try:
            with open(path, "rb") as fh:
                body = fh.read()
        except OSError:
            return self._send(404, {"error": "Not found."})
        extra = {"Content-Disposition": disposition} if disposition else None
        return self._send(200, body, ctype, extra)


def _normalise(raw):
    """Accept 'example.co.za', 'https://example.co.za/page' — reject the rest."""
    candidate = raw if re.match(r"^https?://", raw, re.I) else "https://" + raw
    parts = urllib.parse.urlparse(candidate)
    if parts.scheme not in ("http", "https"):
        return None
    host = parts.hostname or ""
    if "." not in host or not VALID_HOST.match(host):
        return None
    return candidate


def main():
    os.makedirs(REPORTS, exist_ok=True)
    mimetypes.init()

    browser = runtime.chrome_label()
    print(f"Boldpiq Website Audit — http://{HOST}:{PORT}")
    print(f"  reports  : {REPORTS}")
    print(f"  browser  : {browser or 'NOT FOUND — PDF rendering will fail'}")
    try:
        import lighthouse as lh
        print(f"  lighthouse: {lh.available()[0] or 'not found — 4 sections will be skipped'}")
    except Exception as err:
        print(f"  lighthouse: unavailable ({err})")

    print(f"  retention: {RETENTION_DAYS} days" if RETENTION_DAYS > 0 else
          "  retention: disabled")

    threading.Thread(target=_worker, daemon=True, name="scan-worker").start()
    threading.Thread(target=_retention_loop, daemon=True, name="retention").start()
    ThreadingHTTPServer((HOST, PORT), Handler).serve_forever()


if __name__ == "__main__":
    main()
