#!/usr/bin/env python3
"""
Boldpiq Website Audit — web front end.

A small HTTP service that wraps seo_report.py so staff can generate a client
visibility report from a browser instead of a terminal. Standard library only,
matching the rest of the tool.

Design notes worth keeping:

- ONE WORKER, ON PURPOSE. Jobs run strictly one at a time. seoscore.tools' terms
  forbid excessive scanning, and a headless Chrome run is the heaviest thing on
  the box. Serialising also means a queue of three is 2 minutes, not three
  simultaneous Chrome instances fighting for RAM.
- NO AUTHENTICATION HERE. This sits behind Cloudflare Access, the same as n8n.
  Do not expose the port directly to the internet — there is nothing stopping
  anyone from queueing scans.
- The report is generated by shelling out to the CLI rather than importing it,
  so a crash in one scan can never take the server down, and the CLI stays the
  single source of truth for how a report is built.
"""

import json
import mimetypes
import os
import queue
import re
import shutil
import subprocess
import sys
import threading
import time
import urllib.parse
import uuid
from http.server import BaseHTTPRequestHandler, ThreadingHTTPServer

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
sys.path.insert(0, ROOT)

import runtime  # noqa: E402  (needs ROOT on the path first)

REPORTS = os.environ.get("BOLDPIQ_REPORTS") or os.path.join(ROOT, "reports")
PORT = int(os.environ.get("PORT", "8090"))
HOST = os.environ.get("HOST", "0.0.0.0")
# Courtesy gap between consecutive scans, on top of running them one at a time.
JOB_GAP_SECONDS = int(os.environ.get("BOLDPIQ_JOB_GAP", "6"))
JOB_TIMEOUT = int(os.environ.get("BOLDPIQ_JOB_TIMEOUT", "600"))
MAX_JOBS_KEPT = 200

VALID_HOST = re.compile(r"^[a-zA-Z0-9]([a-zA-Z0-9\-._]{0,251}[a-zA-Z0-9])?$")

_jobs = {}                    # id -> job dict
_jobs_lock = threading.Lock()
_queue = queue.Queue()


# ── job model ────────────────────────────────────────────────────────────────

# The CLI's own progress lines, mapped to something a non-technical person can
# read. If the CLI's wording changes, only this table needs updating.
PROGRESS = [
    ("scanning",            "Scanning the site's structure…",              15),
    ("measuring in chrome", "Measuring real load speed in Chrome…",        40),
    ("rendering pdf",       "Building the PDF report…",                    85),
]


def _new_job(url, client, keyphrase, form_factor, lighthouse):
    job = {
        "id": uuid.uuid4().hex[:12],
        "url": url,
        "client": client,
        "keyphrase": keyphrase,
        "form_factor": form_factor,
        "lighthouse": lighthouse,
        "state": "queued",          # queued | running | done | error
        "message": "Waiting in the queue…",
        "percent": 0,
        "created": time.time(),
        "pdf": None,
        "summary": None,
        "error": None,
    }
    with _jobs_lock:
        _jobs[job["id"]] = job
        if len(_jobs) > MAX_JOBS_KEPT:
            for old in sorted(_jobs.values(), key=lambda j: j["created"])[:20]:
                _jobs.pop(old["id"], None)
    return job


def _set(job, **fields):
    with _jobs_lock:
        job.update(fields)


def _queue_positions():
    """Tell anyone still waiting how many jobs are ahead of them."""
    with _jobs_lock:
        waiting = sorted((j for j in _jobs.values() if j["state"] == "queued"),
                         key=lambda j: j["created"])
    for i, job in enumerate(waiting):
        ahead = i
        _set(job, message="Waiting in the queue…" if not ahead
             else f"Waiting in the queue — {ahead} report{'s' if ahead > 1 else ''} ahead…")


# ── worker ───────────────────────────────────────────────────────────────────

def _run_job(job):
    _set(job, state="running", message="Starting…", percent=5)

    cmd = [sys.executable, "-u", os.path.join(ROOT, "seo_report.py"),
           job["url"], "--out", REPORTS, "--no-desktop"]
    if job["client"]:
        cmd += ["--client", job["client"]]
    if job["keyphrase"]:
        cmd += ["--keyphrase", job["keyphrase"]]
    if job["form_factor"] == "desktop":
        cmd += ["--desktop"]
    if not job["lighthouse"]:
        cmd += ["--no-lighthouse"]

    lines = []
    try:
        proc = subprocess.Popen(cmd, cwd=ROOT, stdout=subprocess.PIPE,
                                stderr=subprocess.STDOUT, text=True, bufsize=1)
    except OSError as err:
        _set(job, state="error", error=f"Could not start the report: {err}")
        return

    deadline = time.time() + JOB_TIMEOUT
    for line in proc.stdout:
        line = line.rstrip()
        lines.append(line)
        low = line.lower()
        for needle, message, percent in PROGRESS:
            if needle in low:
                _set(job, message=message, percent=percent)
        if line.strip().startswith("overall "):
            _set(job, summary=line.strip(), message="Finishing up…", percent=92)
        if time.time() > deadline:
            proc.kill()
            _set(job, state="error",
                 error="The scan took too long and was stopped. The site may be "
                       "very slow, or blocking automated requests.")
            return

    proc.wait()

    pdf = next((ln.strip() for ln in reversed(lines)
                if ln.strip().lower().endswith(".pdf")), None)

    if proc.returncode != 0 or not pdf or not os.path.exists(pdf):
        detail = "\n".join(lines[-6:]).strip() or "No output from the report tool."
        _set(job, state="error", error=detail)
        return

    _set(job, state="done", percent=100, pdf=os.path.basename(pdf),
         message="Report ready.")


def _worker():
    while True:
        job = _queue.get()
        try:
            _run_job(job)
        except Exception as err:                       # never let the worker die
            _set(job, state="error", error=f"Unexpected failure: {err}")
        finally:
            _queue.task_done()
            _queue_positions()
            time.sleep(JOB_GAP_SECONDS)


# ── report listing ───────────────────────────────────────────────────────────

def _recent_reports(limit=25):
    if not os.path.isdir(REPORTS):
        return []
    out = []
    for name in os.listdir(REPORTS):
        if not name.lower().endswith(".pdf"):
            continue
        path = os.path.join(REPORTS, name)
        try:
            stat = os.stat(path)
        except OSError:
            continue
        out.append({"file": name,
                    "site": name.split("-visibility-report-")[0],
                    "size_kb": round(stat.st_size / 1024),
                    "modified": stat.st_mtime})
    out.sort(key=lambda r: r["modified"], reverse=True)
    return out[:limit]


# ── http ─────────────────────────────────────────────────────────────────────

class Handler(BaseHTTPRequestHandler):
    server_version = "BoldpiqAudit/1.0"

    def log_message(self, fmt, *args):               # quieter, still useful
        sys.stderr.write("%s %s\n" % (self.address_string(), fmt % args))

    # -- helpers --
    def _send(self, code, body, ctype="application/json; charset=utf-8",
              extra=None):
        if isinstance(body, (dict, list)):
            body = json.dumps(body).encode()
        elif isinstance(body, str):
            body = body.encode()
        self.send_response(code)
        self.send_header("Content-Type", ctype)
        self.send_header("Content-Length", str(len(body)))
        self.send_header("X-Content-Type-Options", "nosniff")
        self.send_header("Referrer-Policy", "no-referrer")
        for k, v in (extra or {}).items():
            self.send_header(k, v)
        self.end_headers()
        if self.command != "HEAD":
            self.wfile.write(body)

    def _public(self, job):
        keep = ("id", "url", "client", "state", "message", "percent", "pdf",
                "summary", "error")
        with _jobs_lock:
            return {k: job[k] for k in keep}

    # -- routes --
    def do_GET(self):
        path = urllib.parse.urlparse(self.path).path

        if path in ("/", "/index.html"):
            return self._file(os.path.join(HERE, "static", "index.html"),
                              "text/html; charset=utf-8")

        if path == "/api/health":
            chrome = runtime.chrome_label()
            lh_bin, node = None, None
            try:
                import lighthouse as lh
                lh_bin, node = lh.available()
            except Exception:
                pass
            return self._send(200, {
                "ok": bool(chrome),
                "browser": chrome,
                "lighthouse": bool(lh_bin),
                "queued": _queue.qsize(),
            })

        if path == "/api/reports":
            return self._send(200, {"reports": _recent_reports()})

        if path.startswith("/api/job/"):
            job = _jobs.get(path.rsplit("/", 1)[-1])
            if not job:
                return self._send(404, {"error": "No such job."})
            return self._send(200, self._public(job))

        if path.startswith("/download/"):
            name = urllib.parse.unquote(path[len("/download/"):])
            # Basename only — never let a request walk out of the reports dir.
            name = os.path.basename(name)
            target = os.path.join(REPORTS, name)
            if not name.lower().endswith(".pdf") or not os.path.isfile(target):
                return self._send(404, {"error": "Report not found."})
            return self._file(target, "application/pdf",
                              disposition=f'inline; filename="{name}"')

        return self._send(404, {"error": "Not found."})

    def do_HEAD(self):
        self.do_GET()

    def do_POST(self):
        path = urllib.parse.urlparse(self.path).path
        if path != "/api/scan":
            return self._send(404, {"error": "Not found."})

        length = int(self.headers.get("Content-Length") or 0)
        if length > 10_000:
            return self._send(413, {"error": "Request too large."})
        try:
            payload = json.loads(self.rfile.read(length) or "{}")
        except ValueError:
            return self._send(400, {"error": "Malformed request."})

        url = (payload.get("url") or "").strip()
        if not url:
            return self._send(400, {"error": "Enter a website address."})
        url = _normalise(url)
        if not url:
            return self._send(400, {"error":
                                    "That doesn't look like a website address. "
                                    "Try something like clientdomain.co.za"})

        job = _new_job(
            url=url,
            client=(payload.get("client") or "").strip()[:120],
            keyphrase=(payload.get("keyphrase") or "").strip()[:120],
            form_factor="desktop" if payload.get("desktop") else "mobile",
            lighthouse=payload.get("lighthouse", True) is not False,
        )
        _queue.put(job)
        _queue_positions()
        return self._send(202, self._public(job))

    def _file(self, path, ctype, disposition=None):
        try:
            with open(path, "rb") as fh:
                body = fh.read()
        except OSError:
            return self._send(404, {"error": "Not found."})
        extra = {"Content-Disposition": disposition} if disposition else None
        return self._send(200, body, ctype, extra)


def _normalise(raw):
    """Accept 'example.co.za', 'https://example.co.za/page' — reject the rest."""
    candidate = raw if re.match(r"^https?://", raw, re.I) else "https://" + raw
    parts = urllib.parse.urlparse(candidate)
    if parts.scheme not in ("http", "https"):
        return None
    host = parts.hostname or ""
    if "." not in host or not VALID_HOST.match(host):
        return None
    return candidate


def main():
    os.makedirs(REPORTS, exist_ok=True)
    mimetypes.init()

    browser = runtime.chrome_label()
    print(f"Boldpiq Website Audit — http://{HOST}:{PORT}")
    print(f"  reports  : {REPORTS}")
    print(f"  browser  : {browser or 'NOT FOUND — PDF rendering will fail'}")
    try:
        import lighthouse as lh
        print(f"  lighthouse: {lh.available()[0] or 'not found — 4 sections will be skipped'}")
    except Exception as err:
        print(f"  lighthouse: unavailable ({err})")

    threading.Thread(target=_worker, daemon=True, name="scan-worker").start()
    ThreadingHTTPServer((HOST, PORT), Handler).serve_forever()


if __name__ == "__main__":
    main()
